<?php if($user): ?>
    <h2>Edit admin user "<?= $user->first_name . ' ' . $user->last_name ?>"</h2>
<?php else: ?>
    <h2>Add new user</h2>
<?php endif; ?>
<br/>

<form action="<?= $this->url('admin.users.action', ['action' => 'doedit', 'id' => $user ? $user->admin_user_id : 0]) ?>" method="POST">
    <div class="form-group">
        <input type="text" class="form-control" name="first_name" placeholder="First name" value="<?= $user ? $user->first_name : '' ?>">
    </div>

    <div class="form-group">
        <input type="text" class="form-control" name="last_name" placeholder="Last name" value="<?= $user ? $user->last_name : '' ?>">
    </div>

    <div class="form-group" disabled>
        <input type="text" class="form-control" name="email" placeholder="Email" value="<?= $user ? $user->email : '' ?>">
    </div>

    <div class="form-group">
        <input type="password" class="form-control" name="password" placeholder="password" value="">
    </div>

    <div class="form-group">
        <input type="password" class="form-control" name="confirm_password" placeholder="confirm password" value="">
    </div>

    <div class="form-group">
        <select class="form-control" name="status">
            <option value="1" <?= ($user && $user->status == 1) ? 'selected' : '' ?>>Activated</option>
            <option value="0" <?= ($user && $user->status == 0) ? 'selected' : '' ?>>Deactivated</option>
        </select>
    </div>

    <button type="submit" class="btn btn-default">Save</button>
    <a href="<?= $this->url('admin.users') ?>" class="btn btn-default">Cancel</a>
</form>
<br/>