<h2>List of admin users</h2>

<?php if($list->getTotalItemCount() > 0): ?>
    <table class="table table-hover table-striped ">
        <thead>
        <tr>
            <th>Active</th>
            <th>Full Name</th>
            <th>Email</th>
            <th>Last Login</th>
            <th>Created at</th>
            <th></th>
        </tr>
        </thead>
        <tbody>

        <?php foreach($list as $one): ?>
            <tr>
                <td><?= $one->status ? 'Yes' : 'No' ?></td>
                <td><?= $one->first_name ?> <?= $one->last_name ?></td>
                <td><?= $one->email ?></td>
                <td><?= $one->last_login ? date('H:i d.m.Y', strtotime($one->last_login)) : '-' ?></td>
                <td><?= date('d.m.Y', strtotime($one->created_at)) ?></td>
                <td>
                    <a href="<?= $this->url('admin.users', ['id' => $one->admin_user_uuid]) ?>" class="color-dark">
                        <i class="glyphicon glyphicon-pencil"></i>
                    </a>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

    <?= $this->paginationControl($list, 'Sliding', 'admin/pagination', ['route' => 'admin.users']) ?>

<?php else: ?>
    <div class="jumbotron text-center">
        <h3>There is no records!</h3>
    </div>
<?php endif; ?>


