<?php if(isset($event)):?>
    <h2>Edit event</h2>
<?php else: ?>
    <h2>Create new event</h2>
<?php endif; ?>
<br/>

<form action="<?= $this->url('admin.events.action', ['action' => 'doedit', 'id' => $event ? $event->article_id : 0]) ?>" method="POST" class="form articleForm">
    <div class="form-group">
        <input type="text" class="form-control" placeholder="title" name="title" value="<?= $event ? $event->title : ''; ?>" />
    </div>

    <div class="form-group">
        <input type="text" class="form-control" placeholder="publish date" name="published_at" value="<?= $event ? $event->published_at : ''; ?>" />
        <i>format: yyyy-mm-dd H:i:s</i>
    </div>

    <div class="form-group">
        <input type="text" class="form-control" rows="3" placeholder="URL slug" name="slug" value="<?= $event ? $event->slug : ''; ?>">
    </div>

    <div class="form-group">
        <textarea id="body" class="form-control" name="body"><?= $event ? $event->body : '' ?></textarea>
    </div>

    <div class="form-group">
        <input type="text" class="form-control" placeholder="longitude" name="longitude" value="<?= $event ? $event->longitude : ''; ?>" />
    </div>

    <div class="form-group">
        <input type="text" class="form-control" placeholder="latitude" name="latitude" value="<?= $event ? $event->latitude : ''; ?>" />
    </div>

    <div class="form-group">
        <select name="status" id="status" class="form-control">
            <option value="0" <?= $event ? ($event->status == 0 ? 'selected' : '') : '' ?>>Unpublished</option>
            <option value="1" <?= $event ? ($event->status == 1 ? 'selected' : '') : '' ?>>Published</option>
        </select>
    </div>

    <button type="submit" class="btn btn-default">Save</button>
    <a href="<?= $this->url('admin.events') ?>" class="btn btn-default">Cancel</a>
</form><br/>