<?php if(isset($event)):?>
    <h2>Edit event</h2>
<?php else: ?>
    <h2>Create new event</h2>
<?php endif; ?>
<br/>

<form action="<?= $this->url('admin.events.action', ['action' => 'save', 'id' => $event ? $event->article_id : 0]) ?>"
      method="POST" class="form articleForm" enctype="multipart/form-data">
    <div class="form-group">
        <input type="text" class="form-control" placeholder="title" name="title" value="<?= $event ? $event->title : ''; ?>" />
    </div>

    <div class="form-group">
        <input type="text" class="form-control" placeholder="sub title" name="sub_title" value="<?= $event ? $event->sub_title : ''; ?>" />
    </div>

    <div class="form-group">
        <input type="text" class="form-control" placeholder="publish date" name="published_at" value="<?= $event ? $event->published_at : ''; ?>" />
        <i>format: yyyy-mm-dd H:i:s</i>
    </div>

    <div class="form-group">
        <input type="text" class="form-control" rows="3" placeholder="URL slug" name="slug" value="<?= $event ? $event->slug : ''; ?>">
    </div>

    <div class="form-group">
        <textarea id="body" class="form-control" name="body"><?= $event ? $event->body : '' ?></textarea>
    </div>

    <div class="form-group">
        <?php if($event && $event->featured_img): ?>
            <img src="<?= $event->featured_img ?>" style="max-width: 200px;"/>
        <?php endif; ?>
    </div>

    <div class="form-group">
        <label>Featured image</label>
        <input type="file" name="featured_img">
        <p class="help-block">Choose image (png or gif) to be fatured.</p>
    </div>

    <div class="form-group">
        <?php if($event && $event->main_img): ?>
            <img src="<?= $event->main_img ?>" style="max-width: 200px;"/>
        <?php endif; ?>
    </div>

    <div class="form-group">
        <label>Main image</label>
        <input type="file" name="main_img">
        <p class="help-block">Choose image (png or gif) to be main for this event.</p>
    </div>


    <div class="form-group">
        <input type="text" class="form-control" placeholder="longitude" name="longitude" value="<?= $event ? $event->longitude : ''; ?>" />
    </div>

    <div class="form-group">
        <input type="text" class="form-control" placeholder="latitude" name="latitude" value="<?= $event ? $event->latitude : ''; ?>" />
    </div>

    <div class="form-group">
        <select name="status" id="status" class="form-control">
            <option value="0" <?= $event ? ($event->status == 0 ? 'selected' : '') : '' ?>>Unpublished</option>
            <option value="1" <?= $event ? ($event->status == 1 ? 'selected' : '') : '' ?>>Published</option>
        </select>
    </div>

    <div class="form-group">
        <select multiple name="tags[]" style="width: 100%;">
            <?php foreach($tags as $tag): ?>
                <option value="<?= $tag->tag_id ?>" <?= ($event && in_array($tag->tag_id, $event->tags)) ? 'selected' : '' ?>>
                    <?= $tag->name ?>
                </option>
            <?php endforeach; ?>
        </select>
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-default">Save</button>
        <a href="<?= $this->url('admin.events') ?>" class="btn btn-default">Cancel</a>

        <?php if($event): ?>
            <a href="<?= $this->url('admin.events.action', ['action' => 'delete', 'id' => $event->article_id]) ?>"
               onclick="if(!confirm('Are you sure?')){return false;}" class="btn btn-danger pull-right">
                Delete
            </a>
        <?php endif; ?>
    </div>
</form>