coverage_clover:
  - application/packages/Admin/tests/clover.xml
  - application/packages/Article/tests/clover.xml
  - application/packages/Category/tests/clover.xml
  - application/packages/Meetup/tests/clover.xml
  - application/packages/Menu/tests/clover.xml
  - application/packages/Newsletter/tests/clover.xml
  - application/packages/Page/tests/clover.xml
  - application/packages/Std/tests/clover.xml
  - application/packages/Web/tests/clover.xml
json_path: coveralls-upload.json
