<?php
/**
 * @var Zend\View\Renderer\PhpRenderer $this
 */
?>

<?php if(isset($post->article_id) && $post->article_id):?>
    <h2>Edit post</h2>
<?php else: ?>
    <h2>Create new post</h2>
<?php endif; ?>
<br/>

<!-- Make better style with the theme css/html - notify -->
<?php if($errors): ?>
    <?php foreach($errors as $input => $inputErrors): ?>
        <div class="bg-danger" style="padding:0.5em; margin:0.5em;">
            <?= $input ?>
            <ul>
                <?php foreach($inputErrors as  $error): ?>
                    <li><?= $error ?></li>
                <?php endforeach; ?>
            <ul/>
        </div>
    <?php endforeach;?>
    <br/>
<?php endif; ?>

<form action="<?= $this->url('admin.posts.action', ['action' => 'save', 'id' => $post ? $post->article_id : 0]) ?>" method="POST" class="form articleForm" enctype="multipart/form-data">
    <div class="form-group">
        <input type="text" class="form-control" placeholder="title" name="title" value="<?= $post ? $post->title : ''; ?>" />
    </div>

    <div class="form-group">
        <input type="text" class="form-control" placeholder="publish date" name="published_at" value="<?= $post ? $post->published_at : ''; ?>" />
        <i>format: yyyy-mm-dd H:i:s</i>
    </div>

    <div class="form-group">
        <textarea class="form-control" rows="3" placeholder="intro..." name="lead"><?= $post ? $post->lead : ''; ?></textarea>
    </div>

    <div class="form-group">
        <input type="text" class="form-control" rows="3" placeholder="URL slug" name="slug" value="<?= $post ? $post->slug : ''; ?>">
    </div>

    <div class="form-group">
        <textarea id="body" class="form-control" name="body"><?= $post ? $post->body : '' ?></textarea>
    </div>

    <div class="form-group">
        <?php if(isset($post->featured_img) && $post->featured_img): ?>
            <img src="<?= $post->featured_img ?>" style="max-width: 200px;"/>
        <?php endif; ?>
    </div>

    <div class="form-group">
        <label>Featured image</label>
        <input type="file" name="featured_img">
        <p class="help-block">Choose image (png or gif) to be fatured.</p>
    </div>

    <div class="form-group">
        <?php if(isset($post->main_img) && $post->main_img): ?>
            <img src="<?= $post->main_img ?>" style="max-width: 200px;"/>
        <?php endif; ?>
    </div>

    <div class="form-group">
        <label>Main image</label>
        <input type="file" name="main_img">
        <p class="help-block">Choose image (png or gif) to be main for this post.</p>
    </div>

    <div class="form-group">
        <select name="status" id="status" class="form-control">
            <option value="0" <?= $post ? ($post->status == 0 ? 'selected' : '') : '' ?>>Unpublished</option>
            <option value="1" <?= $post ? ($post->status == 1 ? 'selected' : '') : '' ?>>Published</option>
        </select>
    </div>

    <div class="form-group">
        <select multiple name="tags[]" style="width: 100%;">
            <?php foreach($tags as $tag): ?>
                <option value="<?= $tag->tag_id ?>" <?= (isset($post->tags) && in_array($tag->tag_id, $post->tags)) ? 'selected' : '' ?>>
                    <?= $tag->name ?>
                </option>
            <?php endforeach; ?>
        </select>
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-default">Save</button>
        <a href="<?= $this->url('admin.posts') ?>" class="btn btn-default">Cancel</a>

        <?php if($post): ?>
        <a href="<?= $this->url('admin.posts.action', ['action' => 'delete', 'id' => $post->article_id]) ?>"
           onclick="if(!confirm('Are you sure?')){return false;}" class="btn btn-danger pull-right">
            Delete
        </a>
        <?php endif; ?>
    </div>
</form><br/>

<?php
$this->inlineScript()->appendScript("
    $(document).ready(function() {
        initMce('#body', '100%', 300, true);

        $('.articleForm').on('submit', function(e) {
            tinyMCE.triggerSave();
        });
    });
");
?>