<div class="row">
    <h2 class="col-md-6">Posts list</h2>
    <div class="col-md-6">
        <a href="<?= $this->url('admin.posts.action', ['action' => 'edit', 'id' => 0]) ?>" style="margin-top:20px;"
           class="btn btn-default pull-right btn-success"> Create new Post
        </a>
    </div>
</div><br/>

<?php if($list->getTotalItemCount() > 0): ?>
    <table class="table table-hover table-striped ">
        <thead>
        <tr>
            <th>Title</th>
            <th>Published</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($list as $one): ?>
            <tr>
                <td><?= $one->title ?></td>
                <td style="width:90px;"><?= date("d.m.Y", strtotime($one->published_at)); ?></td>
                <td style="width:70px;">
                    <span class="pull-right">
                        <a href="<?= $this->url('admin.posts.action', ['action' => 'edit', 'id' => $one->article_id]) ?>">
                            <i class="glyphicon glyphicon-pencil"></i></a> &nbsp;
                    </span>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

    <?= $this->paginationControl($list, 'Sliding', 'admin/pagination', ['route' => 'admin.posts']) ?>
<?php else: ?>
    <div class="jumbotron text-center">
        <h3>There are no posts!</h3>
    </div>
<?php endif; ?>