<?php if(isset($video->article_id) && $video->article_id):?>
    <h2>Edit video</h2>
<?php else: ?>
    <h2>Create new video</h2>
<?php endif; ?>
<br/>

<!-- Make better style with the theme css/html - notify -->
<?php if($errors): ?>
    <?php foreach($errors as $input => $inputErrors): ?>
        <div class="bg-danger" style="padding:0.5em; margin:0.5em;">
            <?= $input ?>
            <ul>
                <?php foreach($inputErrors as  $error): ?>
                    <li><?= $error ?></li>
                <?php endforeach; ?>
                <ul/>
        </div>
    <?php endforeach;?>
    <br/>
<?php endif; ?>

<form action="<?= $this->url('admin.videos.action', ['action' => 'save', 'id' => $video ? $video->article_id : 0]) ?>"
      method="POST" class="form articleForm" enctype="multipart/form-data">

    <div class="form-group">
        <input type="text" class="form-control" placeholder="title" name="title" value="<?= $video ? $video->title : ''; ?>" />
    </div>

    <div class="form-group">
        <input type="text" class="form-control" placeholder="publish date" name="published_at" value="<?= $video ? $video->published_at : ''; ?>" />
        <i>format: yyyy-mm-dd H:i:s</i>
    </div>

    <div class="form-group">
        <textarea class="form-control" rows="3" placeholder="intro..." name="lead"><?= $video ? $video->lead : ''; ?></textarea>
    </div>

    <div class="form-group">
        <div class="videoPreview">
            <?= $video ? $video->embed_code : ''; ?>
        </div>
        <textarea class="form-control embedCode" rows="3" placeholder="embed code..." name="embed_code"><?= $video ? $video->embed_code : ''; ?></textarea>
    </div>

    <div class="form-group">
        <input type="text" class="form-control" rows="3" placeholder="URL slug" name="slug" value="<?= $video ? $video->slug : ''; ?>">
    </div>

    <div class="form-group">
        <textarea id="body" class="form-control" name="body"><?= $video ? $video->body : '' ?></textarea>
    </div>

    <div class="form-group">
        <?php if(isset($video->featured_img) && $video->featured_img): ?>
            <img src="<?= $video->featured_img ?>" style="max-width: 200px;"/>
        <?php endif; ?>
    </div>

    <div class="form-group">
        <label>Featured image</label>
        <input type="file" name="featured_img">
        <p class="help-block">Choose image (png or gif) to be fatured.</p>
    </div>

    <div class="form-group">
        <?php if(isset($video->main_img) && $video->main_img): ?>
            <img src="<?= $video->main_img ?>" style="max-width: 200px;"/>
        <?php endif; ?>
    </div>

    <div class="form-group">
        <label>Main image</label>
        <input type="file" name="main_img">
        <p class="help-block">Choose image (png or gif) to be main for this video.</p>
    </div>

    <div class="form-group">
        <select name="status" id="status" class="form-control">
            <option value="0" <?= $video ? ($video->status == 0 ? 'selected' : '') : '' ?>>Unpublished</option>
            <option value="1" <?= $video ? ($video->status == 1 ? 'selected' : '') : '' ?>>Published</option>
        </select>
    </div>

    <div class="form-group">
        <select multiple name="tags[]" style="width: 100%;">
            <?php foreach($tags as $tag): ?>
                <option value="<?= $tag->tag_id ?>" <?= (isset($video->tags) && in_array($tag->tag_id, $video->tags)) ? 'selected' : '' ?>>
                    <?= $tag->name ?>
                </option>
            <?php endforeach; ?>
        </select>
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-default">Save</button>
        <a href="<?= $this->url('admin.videos') ?>" class="btn btn-default">Cancel</a>

        <?php if(isset($video->article_id) && $video->article_id): ?>
        <a href="<?= $this->url('admin.videos.action', ['action' => 'delete', 'id' => $video->article_id]) ?>"
           onclick="if(!confirm('Are you sure?')){return false;}" class="btn btn-danger pull-right">
            Delete
        </a>
        <?php endif; ?>
    </div>
</form><br/>

<?php
/**
 * @var Zend\View\Renderer\PhpRenderer $this
 */
//$this->inlineScript()->appendScript("
//    $(document).ready(function() {
//        initMce('#body', '100%', 300, true);
//
//        $('.articleForm').on('submit', function(e) {
//            tinyMCE.triggerSave();
//        });
//
//        var oldVal = '';
//        $('.embedCode').on('change textInput input', function(e) {
//            if($(this).hasClass('embedCode') && $(this).html().length){
//                setTimeout(function () {
//                    console.log($($('.embedCode').text()).attr('src'));
//                }, 100);
//            var iframe = '<iframe width=\"560\" height=\"315\" frameborder=\"0\" allowfullscreen></iframe>';
//            $('.videoPreview').html(iframe);
//            console.log($($('.embedCode').text()).attr('src'));
//            $('.videoPreview iframe').attr('src', $($('.embedCode').text()).attr('src'));
//            }
//        });
//    });
//");
?>

<script src="/js/tinymce/tinymce.min.js"></script>
<script src="/js/initTinyMce.js"></script>

<?php
$this->inlineScript()->appendScript("
    $(document).ready(function() {
        initMce('#body', '100%', 300, true);

        $('.articleForm').on('submit', function(e) {
            tinyMCE.triggerSave();
        });
    });
");
?>
