<article id="post-1587" class="group post-1587 post type-post status-publish format-standard has-post-thumbnail hentry category-vesti">
    <div class="post-inner post-hover">

        <div class="post-thumbnail">
            <a href="/single/<?=$article->slug?>/" title="<?=$article->title?>">
                <img src="<?=$article->featured_img?>" class="attachment-thumb-medium size-thumb-medium wp-post-image" alt="<?=$article->title?>" width="520" height="245">																			</a>
            <a class="post-comments" href="http://phpsrbija.rs/rezultati-ankete-zene-i-devojke-u-it-svetu/#respond"><span><i class="fa fa-comments-o"></i>0</span></a>
        </div><!--/.post-thumbnail-->

        <div class="post-meta group">
            <p class="post-category"><a href="/clanci/" rel="category tag">Svi članci</a></p>
            <p class="post-date"><?=date('d M, Y', strtotime($article->published_at))?></p>
        </div><!--/.post-meta-->

        <h2 class="post-title">
            <a href="/single/<?=$article->slug?>/" rel="bookmark" title="<?=$article->title?>"><?=$article->title?></a>
        </h2><!--/.post-title-->

        <div class="entry excerpt">
            <?=$article->lead?>
        </div><!--/.entry-->

    </div><!--/.post-inner-->
</article><!--/.post-->