<header id="header">

    <nav class="nav-container group" id="nav-topbar">
        <div class="nav-toggle"><i class="fa fa-bars"></i></div>
        <div class="nav-text"><!-- put your mobile menu text here --></div>
        <div class="nav-wrap container"><ul id="menu-topmeni" class="nav container-inner group"><li id="menu-item-165" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-165"><a href="http://phpsrbija.rs/">Početna</a></li>
                <li id="menu-item-1110" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-1110"><a href="/clanci/">Članci</a></li>
                <li id="menu-item-1378" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1378"><a href="http://phpsrbija.rs/video/">Video</a></li>
                <li id="menu-item-1072" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1072"><a href="/zdravo-svete/">O nama</a></li>
                <li id="menu-item-168" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-168"><a href="/udruzenje/statut/">Statut</a></li>
                <li id="menu-item-896" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-896"><a href="/udruzenje/prikljuci-se/">Priključi se</a></li>
                <li id="menu-item-1102" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-1102"><a href="http://phpsrbija.rs/anketa/">Ankete</a>
                    <ul class="sub-menu">
                        <li id="menu-item-1103" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1103"><a href="http://phpsrbija.rs/rezultati_ankete_1/">Rezultati ankete &#8211; stanje PHP programera</a></li>
                    </ul>
                </li>
                <li id="menu-item-166" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-166"><a href="/kontakt/">Kontakt</a></li>
                <li id="menu-item-1242" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1242"><a href="http://soliday.phpsrbija.rs/">SOLIDay 2015</a></li>
                <li id="menu-item-1519" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1519"><a href="http://conf2016.phpsrbija.rs/">Conf 2016</a></li>
            </ul></div>
        <div class="container">
            <div class="container-inner">

            </div><!--/.container-inner-->
        </div><!--/.container-->
    </nav><!--/#nav-topbar-->

    <div class="container group">
        <div class="container-inner">
            <a href="http://conf2017.phpsrbija.rs/" rel="home" target="_blank">
                <img class="site-image" src="/wp-includes/images/php-sajt1.jpg" alt="">
            </a>
        </div><!--/.container-inner-->
    </div><!--/.container-->

</header><!--/#header-->