<?php //var_dump($article); ?>


<div class="container" id="page">
    <div class="container-inner">
        <div class="main">
            <div class="main-inner group">
                <section class="content">

                    <div class="page-title pad group">

                        <h2>Priključi se</h2>


                    </div><!--/.page-title-->
                    <div class="pad group">


                        <article class="group post-36 page type-page status-publish hentry">


                            <div class="entry themeform">
                                <p><strong>Želiš da se uključiš i da zajedno sa nama radiš na jačanju PHP zajednice u Srbiji? Postoje dva načina. Na tebi je da odabereš koji ti više odgovara.</strong></p>
                                <ol>
                                    <li>Član Udruženja</li>
                                    <li>Saradnik</li>
                                </ol>
                                <p>Od članova i saradnika očekujemo posvećenost, entuzijazam i pozitivnu energiju jer samo tako možemo doći do rezultata i ciljeva kojima stremimo.</p>
                                <p>Upravni odbor Udruženja će razmotriti vašu prijavu i blagovremeno vam odgovoriti. Mi nažalost nismo u mogućnosti da prihvatimo svaku prijavu već samo one za koje procenimo da mogu doprineti radu i razvoju Udruženja.</p>
                                <h4>Postani Član Udruženja PHP Srbija</h4>
                                <p>Članovi Udruženja su spremi da ulože svoje vreme, znanje i energiju u ostvarivanje zajedničkih ciljeva.</p>
                                <p>Članovi mogu da biraju i da budu birani za obavljanje različitih funkcija u Udruženju. Svaki član je član skupštine koja ima značajnu ulogu u odlučivanju. Pre slanja prijave za članstvo molimo vas da pročitate <a href="http://phpsrbija.rs/udruzenje/statut/">statut Udruženja</a>.</p>
                                <p>Članovi su u obavezi da plaćaju godišnju članarinu koja u ovom trenutku iznosi 4 000 RSD i 2000 RSD za nezaposlene i studente a koja se može izmiriti i iz dva dela. Članarina je izvor prihoda za deo aktivnosti Udruženja i koristi se za finansiranje projekata Udruženja.</p>
                                <h4>Budi naš saradnik</h4>
                                <p>Ako želiš da doprineseš Udruženju tako što ćeš učestvovati u našim projektima a pri tome ne želiš da učestvuješ u odlučivanju onda možeš biti naš saradnik.</p>
                                <p>Potrebni su nam saradnici za pisanje članaka na blogu Udruženja, predavači za radionice, organizaciju meetupa i drugih događaja, razvoju open source rešenja, lokalizaciji softvera, administrativne poslove ali i za druge projekte koji će se aktivirati po potrebi.</p>
                                <p>U formi koja se nalazi ispod napiši nam što više informacija o sebi. Reci nam koji su to projekti u kojima bi želeo da učestvuješ. Daj nam dobar razlog da baš ti budeš član ili saradnik Udruženja PHP Srbija.</p>
                                <div role="form" class="wpcf7" id="wpcf7-f128-p36-o1" dir="ltr">
                                    <div class="screen-reader-response"></div>
                                    <form action="/udruzenje/prikljuci-se/#wpcf7-f128-p36-o1" method="post" class="wpcf7-form" enctype="multipart/form-data" novalidate="novalidate">
                                        <div style="display: none;">
                                            <input name="_wpcf7" value="128" type="hidden">
                                            <input name="_wpcf7_version" value="4.6" type="hidden">
                                            <input name="_wpcf7_locale" value="" type="hidden">
                                            <input name="_wpcf7_unit_tag" value="wpcf7-f128-p36-o1" type="hidden">
                                            <input name="_wpnonce" value="59707a5501" type="hidden">
                                        </div>
                                        <p>Ime i prezime <span style="color:red">*</span><br>
                                            <span class="wpcf7-form-control-wrap your-name"><input name="your-name" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required" aria-required="true" aria-invalid="false" type="text"></span>
                                        </p>
                                        <p>Tvoj e-mail <span style="color:red">*</span><br>
                                            <span class="wpcf7-form-control-wrap email-971"><input name="email-971" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-email wpcf7-validates-as-required wpcf7-validates-as-email" aria-required="true" aria-invalid="false" type="email"></span>
                                        </p>
                                        <p>Tvoj telefon <span style="color:red">*</span><br>
                                            <span class="wpcf7-form-control-wrap text-492"><input name="text-492" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required" aria-required="true" aria-invalid="false" type="text"></span>
                                        </p>
                                        <p>Linkedin profil<br>
                                            <span class="wpcf7-form-control-wrap text-970"><input name="text-970" value="" size="40" class="wpcf7-form-control wpcf7-text" aria-invalid="false" type="text"></span>
                                        </p>
                                        <p>Napiši nam zašto želiš da budeš deo naše zajednice <span style="color:red">*</span><br>
                                            <span class="wpcf7-form-control-wrap your-message"><textarea name="your-message" cols="40" rows="10" class="wpcf7-form-control wpcf7-textarea wpcf7-validates-as-required" aria-required="true" aria-invalid="false"></textarea></span>
                                        </p>
                                        <p>Prikači svoj CV uz prijavu (doc, docx, pdf)<span style="color:red">*</span><br>
                                            <span class="wpcf7-form-control-wrap file-627"><input name="file-627" size="40" class="wpcf7-form-control wpcf7-file wpcf7-validates-as-required" aria-required="true" aria-invalid="false" type="file"></span>
                                        </p>
                                        <p>
                                            Pokaži nam da nisi bot <span style="color:red">*</span><br>
                                            <span class="wpcf7-form-control-wrap quiz-230"><label><span class="wpcf7-quiz-label">1+1=?</span> <input name="quiz-230" size="40" class="wpcf7-form-control wpcf7-quiz" autocomplete="off" aria-required="true" aria-invalid="false" type="text"></label><input name="_wpcf7_quiz_answer_quiz-230" value="aa16b50d66a9970f0a23c2810d732555" type="hidden"></span>
                                        </p>
                                        <p><input value="Priključi se" class="wpcf7-form-control wpcf7-submit" type="submit"><span class="ajax-loader"></span></p>
                                        <p style="font-size:12px">* obavezna polja</p>
                                        <div class="wpcf7-response-output wpcf7-display-none"></div></form></div>
                                <div class="clear"></div>
                            </div><!--/.entry-->

                        </article>



                    </div><!--/.pad-->

                </section>

                <?= $this->partial('legacy::sidebar'); ?>

            </div><!--/.main-inner-->
        </div><!--/.main-->
    </div><!--/.container-inner-->
</div><!--/.container-->