<link rel='stylesheet' id='buttons-css'  href='/wp-includes/css/buttons.min.css?ver=4.7.2' type='text/css' media='all' />
<script type='text/javascript' src='/wp-includes/js/jquery.fancybox.pack.js?ver=4.7.2'></script>
<script type='text/javascript' src='/wp-includes/js/light.js?ver=4.7.2'></script>
<!--<script type='text/javascript' src='/wp-content/themes/hueman/js/jquery.jplayer.min.js?ver=4.7.2'></script>-->
<!--<script type='text/javascript' src='/wp-content/themes/hueman/js/scripts.js?ver=4.7.2'></script>-->
<!--<script type='text/javascript' src='/wp-content/themes/hueman/js/jquery.sharrre.min.js?ver=4.7.2'></script>-->
<script type='text/javascript'>
    /* <![CDATA[ */
    var FB_WP=FB_WP||{};FB_WP.queue={_methods:[],flushed:false,add:function(fn){FB_WP.queue.flushed?fn():FB_WP.queue._methods.push(fn)},flush:function(){for(var fn;fn=FB_WP.queue._methods.shift();){fn()}FB_WP.queue.flushed=true}};window.fbAsyncInit=function(){FB.init({"xfbml":true});if(FB_WP && FB_WP.queue && FB_WP.queue.flush){FB_WP.queue.flush()}}
    /* ]]> */
</script>
<script type="text/javascript">(function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(d.getElementById(id)){return}js=d.createElement(s);js.id=id;js.src="http:\/\/connect.facebook.net\/sr_RS\/all.js";fjs.parentNode.insertBefore(js,fjs)}(document,"script","facebook-jssdk"));</script>
<script type='text/javascript' src='/wp-includes/js/wp-embed.min.js?ver=4.7.2'></script>

<script type='text/javascript' src='/wp-includes/js/utils.min.js?ver=4.7.2'></script>
<script type='text/javascript' src='/wp-includes/js/wp-a11y.min.js?ver=4.7.2'></script>

<script type='text/javascript' src='/wp-includes/js/wplink.min.js?ver=4.7.2'></script>
<script type='text/javascript' src='/wp-includes/js/core.min.js?ver=1.11.4'></script>
<script type='text/javascript' src='/wp-includes/js/widget.min.js?ver=1.11.4'></script>
<script type='text/javascript' src='/wp-includes/js/position.min.js?ver=1.11.4'></script>
<script type='text/javascript' src='/wp-includes/js/menu.min.js?ver=1.11.4'></script>
<script type='text/javascript' src='/wp-includes/js/autocomplete.min.js?ver=1.11.4'></script>