<?php
/**
 * @var \Zend\Paginator\Paginator $paginator
 */


?><div class="container" id="page">
    <div class="container-inner">
        <div class="main">
            <div class="main-inner group">
                <section class="content">

                    <div class="page-title pad group">
                        <h1><i class="fa fa-folder-open"></i>Kategorija: <span>Svi članci</span></h1>
                    </div><!--/.page-title-->
                    <div class="pad group">
                        <div class="post-list group">
                            <?php
                                foreach ($paginator as $key => $article):
                                    if ($key % 2 === 0) {?>
                            <div class="post-row">
                            <?php   }
                                    echo $this->partial('legacy::article-list', ['article' => $article, 'upload' => $upload]);
                                    if ($key % 2 === 1) {?>
                            </div>
                            <?php   }
                                endforeach;
                            ?>
                        </div><!--/.post-list-->

                        <nav class="pagination group">
                            <div class="wp-pagenavi">
                                <?php $totalPages = 4; ?>
                                <span class="pages">Stranica <?=$paginator->getCurrentPageNumber()?> od <?=$totalPages?></span>
                                <?php for ($i=1; $i<5; $i++): ?>
                                    <?php if ($paginator->getCurrentPageNumber() === $i): ?>
                                    <span class="current"><?=$paginator->getCurrentPageNumber()?></span>
                                    <?php else: ?>
                                    <a class="page larger" href="/clanci/page/<?=$i?>/"><?=$i?></a>
                                    <?php endif ?>
                                <?php endfor ?>
                                <?php if ($paginator->getCurrentPageNumber() < 4): ?>
                                <a class="nextpostslink" rel="next" href="/clanci/page/<?=$paginator->getCurrentPageNumber()+1?>/">»</a>
                                <?php endif ?>
                            </div>	</nav><!--/.pagination-->

                    </div><!--/.pad-->
                </section>

                <?= $this->partial('legacy::sidebar'); ?>

            </div><!--/.main-inner-->
        </div><!--/.main-->
    </div><!--/.container-inner-->
</div><!--/.container-->