<div class="container" id="page">
    <div class="container-inner">
        <div class="main">
            <div class="main-inner group">
                <section class="content">

                    <div class="page-title pad group">

                        <h2>Statut</h2>


                    </div><!--/.page-title-->
                    <div class="pad group">


                        <article class="group post-121 page type-page status-publish hentry">


                            <div class="entry themeform">
                                <p style="text-align: justify;">Na osnovu člana 12 Zakona o udruženjima(„Službeni glasnik RS“ br. 51/2009 od 14. 07. 2009. godine), na osnivačkoj skupštini održanoj 25.10.2012 godine, usvojen je sledeći</p>
                                <p style="text-align: center;"><strong>&nbsp;STATUT „PHP SRBIJA“</strong></p>
                                <p style="text-align: center;"><strong>Član 1.</strong></p>
                                <p style="text-align: justify;">Udruženje „PHP Srbija“ (u daljem tekstu: „Udruženje“) je dobrovoljno, nevladino i nedobitno udruženje, osnovano na neodređeno vreme radi ostvarivanja ciljeva i aktivnosti u oblasti informacionih nauka i tehnologija.</p>
                                <p style="text-align: center;"><strong>Član 2.</strong></p>
                                <p style="text-align: justify;">Neposredni ciljevi Udruženja su:</p>
                                <ul>
                                    <li>Okupljanje stručnjaka i entuzijasta u oblasti informacionih tehnologija, strukom ili interesovanjem vezanih za PHP tehnologiju u jedinstvenu zajednicu</li>
                                    <li>Stvaranje i održavanje jedinstvenog registra PHP inženjera i stručnjaka, kao i IT kompanija koje u okviru svog poslovanja koriste PHP tehnologiju</li>
                                    <li>Stvaranje uslova za učešće članova zajednice i zajednice u celini u naučno-istraživačkim projektima i stvaralačkom radu</li>
                                    <li>Stvaranje uslova za učešće članova zajednice i zajednice u celini na stručnim skupovima, seminarima, takmičenjima i sajmovima</li>
                                    <li>Organizovanje stručnih skupova, seminara i sajmova, kao i takmičenja u oblasti informacionih tehnologija</li>
                                    <li>Stvaranje uslova za praktikovanje znanja i veština u oblasti informacionih tehnologija u okviru projekata i timova zajednice</li>
                                    <li>Razmena znanja i iskustava između članova zajednice kao i zajednice u celini sa drugim stručnim udruženjima i zajednicama</li>
                                    <li>Kontinualna edukacija šire zajednice u oblasti informacionih tehnologija, sa fokusom na PHP tehnologiju</li>
                                </ul>
                                <p style="text-align: center;"><strong>Član 3.</strong></p>
                                <p style="text-align: justify;">Radi ostvarivanja svojih ciljeva Udruženje naročito:</p>
                                <ul>
                                    <li>Prikuplja i obrađuje naučnu i stručnu literaturu iz oblasti informacionih nauka i tehnologija</li>
                                    <li>Organizuje, samostalno ili u saradnji sa drugim institucijama, stručne skupove, savetovanja, sajmove, treninge, takmičenja, seminare i druge oblike edukacije u oblasti informacionih nauka i tehnologija</li>
                                    <li>Objavljuje knjige i druge publikacije iz oblasti informacionih nauka i tehnologija i srodnih disciplina, u skladu sa zakonom</li>
                                    <li>Sarađuje sa univerzitetima, školama, stručnim udruženjima i drugim organizacijama od interesa u zemlji i inostranstvu koje se bave informacionim naukama i tehnogijama</li>
                                    <li>Kontaktira sa preduzećima, privatnim poslodavcima i ustanovama u cilju upoznavanja i unapređivanja poslovanja novim idejama i rešenjima iz oblasti informacionih nauka i tehnologija</li>
                                    <li>Učestvuje na javim tenderima i konkursima u režiji države Srbije ili preduzećima u zemlji i inostranstvu</li>
                                </ul>
                                <p style="text-align: center;"><strong>Član 4.</strong></p>
                                <p style="text-align: justify;">Puno ime Udruženja je: Udruženje građana „PHP Srbija“. Puno ime Udruženja na engleskom jeziku je „PHP Serbia“. Skraćeno ime Udruženja je „PHP Srbija“.</p>
                                <p style="text-align: justify;">Sedište Udruženja je u Beogradu, ulica Peđe Milosavljevića 28/14. Udruženje svoju delatnost ostvaruje na teritoriji Republike Srbije i međunarodno.</p>
                                <p style="text-align: center;"><strong>&nbsp;Član 5.</strong></p>
                                <p style="text-align: justify;">Simboli vizuelnog identiteta Udruženja su logo i pečat Udruženja.</p>
                                <p style="text-align: justify;">Logo Udruženja sadrži skraćeno ime Udruženja, i ima sledeći izgled:</p>
                                <p style="text-align: center;"><a href="http://phpsrbija.rs/udruzenje/o-nama/php_sajt/" rel="attachment wp-att-49"><img alt="php_sajt" src="http://phpsrbija.rs/wp-content/uploads/2012/11/php_sajt.png" width="132" height="91"></a></p>
                                <p style="text-align: justify;">Pečat Udruženja je okruglog oblika i na njemu ćiriličnim pismom piše:</p>
                                <ul>
                                    <li>U centru pečata „PHP Srbija”.</li>
                                    <li>U krugu uz ivicu pečata „UDRUŽENjE GRAĐANA“.</li>
                                </ul>
                                <p style="text-align: center;"><strong>Član 6.</strong></p>
                                <p style="text-align: justify;">Član Udruženja može biti svako fizičko lice koje prihvata ciljeve Udruženja i podnese pisanu prijavu za učlanjenje Upravnom odboru Udruženja.</p>
                                <p style="text-align: justify;">Odluku o prijemu u članstvo donosi Upravni odbor i o tome obaveštava podnosioca prijave i Skupštinu Udruženja u roku od 7 dana od donošenja odluke.</p>
                                <p style="text-align: center;"><strong>Član 7.</strong></p>
                                <p style="text-align: justify;">Član može prekinuti članstvo podnošenjem pisane izjave o istupanju Upravnom odboru.</p>
                                <p style="text-align: justify;">Članstvo u Udruženju može prestati odlukom Upravnog odbora i to u slučaju duže neaktivnosti člana, nepoštovanja odredba ovog Statuta ili narušavanja ugleda Udruženja.</p>
                                <p style="text-align: justify;">Odluku o ispunjenju uslova za prestanak članstva donosi Upravni odbor Udruženja dvotrećinskom većinom.</p>
                                <p style="text-align: justify;">Član može podneti žalbu na osnovu donešene odluke o izbacivanju. Rok za podnošenje žalbe je 15 dana od datuma donošenja odluke o izbacivanju. Skupština je dužna da ponovi glasanje o udaljavanju člana, na nivou celog Udruženja, na prvom sledećem formalnom zasedanju.</p>
                                <p style="text-align: center;"><strong>Član 8.</strong></p>
                                <p style="text-align: justify;">Članovi Udruženja imaju sledeća prava i obaveze:</p>
                                <p style="text-align: justify;">Prava člana Udruženja su da:</p>
                                <ul>
                                    <li>ravnopravno sa drugim članovima učestvuje u ostvarivanju ciljeva Udruženja,</li>
                                    <li>neposredno učestvuje u odlučivanju na Skupštini, kao i preko organa Udruženja,</li>
                                    <li>bira i bude biran u organe Udruženja,</li>
                                    <li>bude blagovremeno i u potpunosti informisan o radu i aktivnostima Udruženja.</li>
                                </ul>
                                <p style="text-align: justify;">Obaveze člana Udruženja su da:</p>
                                <ul>
                                    <li>aktivno doprinosi ostvarivanju ciljeva Udruženja,</li>
                                    <li>učestvuje, u skladu sa interesovanjem i prihvaćenom odgovornošću, u aktivnostima Udruženja,</li>
                                    <li>plaća članarinu,</li>
                                    <li>obavlja druge poslove koje mu poveri Upravni odbor,</li>
                                    <li>se ponaša u skladu sa vrednostima Udruženja i doprinosi pozitivnom imidžu Udruženja.</li>
                                </ul>
                                <p style="text-align: center;"><strong>Član 9.</strong></p>
                                <p style="text-align: justify;">Ukoliko ne poštuje prava i obaveze utvrđene Statutom Udruženja, član može snositi sankcije.</p>
                                <p style="text-align: justify;">Sankcije članovima Udruženja mogu biti:</p>
                                <ul>
                                    <li>Smena sa funkcije u Upravnom odboru ili projektnom timu,</li>
                                    <li>Zabrana svih aktivnosti u ime Udruženja,</li>
                                    <li>Isključenje iz Udruženja.</li>
                                </ul>
                                <p style="text-align: justify;">Predlog o sankcionisanju može podneti svaki član Udruženja Upravnom odboru pisanim putem.</p>
                                <p style="text-align: justify;">Odluku o sankcijama donosi Upravni odbor Udruženja dvotrećinskom većinom u roku od 7 dana od podnošenja predloga o sankcionisanju.</p>
                                <p style="text-align: center;"><strong>Član 10.</strong></p>
                                <p style="text-align: justify;">Član Udruženja ima pravo da bude obaveštavan o radu Udruženja na način definisan Internim aktima Udruženja.</p>
                                <p style="text-align: center;"><strong>Član 11.</strong></p>
                                <p style="text-align: justify;">Počasni članovi su članovi Udruženja koji imaju posebna prava i obaveze koje se razlikuju od prava i obaveza članova Udruženja.</p>
                                <p style="text-align: justify;">Počasni član Udruženja može biti bilo koje fizičko lice, koje je svojim radom posebno doprinelo razvoju Udruženja.</p>
                                <p style="text-align: justify;">Odluku o počasnom članstvu jednoglasno donosi Upravni odbor, na predlog bilo kog člana Udruženja.</p>
                                <p style="text-align: justify;">Odluku o pravima i obavezama Počasnih članova donosi Upravni odbor, dvotrećinskom većinom u roku od mesec dana od prijema predloga za Počasno članstvo. Prava i obaveze Počasnih članova se definišu pojedinačno za svakog Počasnog člana i beleže se u Internim aktima.</p>
                                <p style="text-align: justify;">Odluku o prekidu statusa Počasnog člana jednoglasno donosi Upravni odbor posebnim Internim aktom, uz obrazloženje na Skupštini.</p>
                                <p style="text-align: center;"><strong>&nbsp;Član 12.</strong></p>
                                <p style="text-align: justify;">Organi Udruženja su Skupština Udruženja (u daljem tekstu „Skupština“), Upravni odbor Udruženja (u daljem tekstu „Upravni odbor“) i Nadzorni odbor Udruženja (u daljem tekstu „Nadozorni odbor“).</p>
                                <p style="text-align: center;"><strong>Član 13.</strong></p>
                                <p style="text-align: justify;">Skupština je najviši organ Udruženja i sačinjavaju je svi članovi Udruženja.</p>
                                <p style="text-align: justify;">Redovna sednica Skupštine održava se jednom godišnje. Vanredna sednica Skupštine može biti održana na predlog Upravnog odbora, kao i na inicijativu najmanje jedne trećine članova Udruženja. Inicijativa se podnosi Upravnom odboru u pisanom obliku uz obavezan predlog dnevnog reda. Upravni odbor je dužan da Skupštinu organizuje u roku od mesec dana od podnošenja inicijative.</p>
                                <p style="text-align: justify;">Sednicu Skupštine saziva predsednik Upravnog odbora, pisanim obaveštenjem koje sadrži mesto i vreme održavanja Skupštine i predlog dnevnog reda. Sednicom predsedava lice odabrano od strane Upravnog odbora koji iz reda članova imenuje zapisničara koji je dužan da sastavi zapisnik sa Skupštine.</p>
                                <p style="text-align: justify;">Predsedavajući Skupštine može biti svaki član Udruženja.</p>
                                <p style="text-align: center;"><strong style="text-align: center;">Član 14.</strong></p>
                                <p style="text-align: justify;">Skupština Udruženja:</p>
                                <ul>
                                    <li>Usvaja Statut Udruženja, kao i izmene i dopune Statuta Udruženja,</li>
                                    <li>Usvaja akte Udruženja,</li>
                                    <li>Odlučuje glasanjem o pitanjima koje joj na razmatranje dostavlja Upravni odbor,</li>
                                    <li>Odlučuje o visini godišnje članarine,</li>
                                    <li>Bira i razrešava lica ovlašćena za zastupanje Udruženja,</li>
                                    <li>Bira i razrešava članove Upravnog odbora,</li>
                                    <li>Bira i razrešava članove Nadzornog odbora,</li>
                                    <li>Utvrđuje politiku delovanja Udruženja,</li>
                                    <li>Donosi plan razvoja Udruženja,</li>
                                    <li>Usvaja godišnji plan rada,</li>
                                    <li>Usvaja godišnji finansijski plan i finansijski izveštaj o aktivnostima Udruženja,</li>
                                    <li>Donosi odluku o statusnim promenama i prestanku rada Udruženja.</li>
                                    <li>Odlučuje o udruživanju u saveze i druge asocijacije</li>
                                </ul>
                                <p style="text-align: justify;">Na Skupštini mogu biti donete punopravne odluke ako je prisutno više od polovine ukupnog broja članova Skupštine. Skupština odlučuje o pitanjima iz svoje nadležnosti dvotrećinskom većinom glasova prisutnih članova.</p>
                                <p style="text-align: center;"><strong>Član 15.</strong></p>
                                <p style="text-align: justify;">Upravni odbor je izvršni organ Udruženja, koji se stara o sprovođenju ciljeva Udruženja koji su utvrđeni ovim Statutom.</p>
                                <p style="text-align: justify;">Upravni odbor sačinjava minimalno tri, a maksimalno deset članova Udruženja, koje biraju i razrešavaju članovi Udruženja na Skupštini Udruženja.</p>
                                <p style="text-align: justify;">Upravni odbor čine:</p>
                                <ul>
                                    <li>Predsednik Upravnog odbora</li>
                                    <li>Podpredsednik Upravnog odbora</li>
                                    <li>Ostali članovi Upravnog odbora</li>
                                </ul>
                                <p style="text-align: justify;">Mandat članova Upravnog odbora traje godinu dana i mogu se ponovo birati na istu funkciju.</p>
                                <p style="text-align: justify;">Upravni odbor iz redova svojih članova dvotrećinskom većinom bira Predsednika i Podpredsednika.</p>
                                <p style="text-align: center;"><strong>Član 16.</strong></p>
                                <p style="text-align: justify;">Članovi Upravnog odbora imaju sledeća prava i obaveze:</p>
                                <p style="text-align: justify;">Prava člana Upravnog odbora su:</p>
                                <ul>
                                    <li>Pravo glasa u odlučivanju,</li>
                                    <li>Pravo da pokrene zahtev za glasanje o nepoverenju za bilo kog člana Upravnog odbora i preispitivanju korektnosti rada člana.</li>
                                </ul>
                                <p style="text-align: justify;">Obaveze člana Upravnog odbora su:</p>
                                <ul>
                                    <li>Da vrši funkciju u skladu sa opisom funkcije, definisane Internim aktima,</li>
                                    <li>Da poštuje i izvršava odluke Upravnog odbora i Skupštine,</li>
                                    <li>Da brine o radu, imidžu, ciljevima, vrednostima, misiji i viziji Udruženja,</li>
                                    <li>Da na kraju svog mandata prenese stečena znanja članu Udruženja koji preuzima njegovu funkciju,</li>
                                    <li>Mandat člana Upravnog odbora traje godinu dana, osim ukoliko okolnosti ne zahtevaju drugačije.</li>
                                </ul>
                                <p style="text-align: justify;">Ukoliko član Upravnog odbora ne poštuje svoje obaveze ili se ne ponaša u skladu sa svojim obavezama, predsedavajući Upravnog odboara dužan je da pokrene pitanje poverenja i sprovede neophodne mere.</p>
                                <p style="text-align: center;"><strong>Član 17.</strong></p>
                                <p style="text-align: justify;">&nbsp;Upravni odbor:</p>
                                <ul>
                                    <li>Rukovodi radom Udruženja i donosi odluke radi ostvarivanja ciljeva Udruženja,</li>
                                    <li>Organizuje redovno obavljanje delatnosti Udruženja,</li>
                                    <li>Poverava zaduženja pojedinim članovima, u skladu sa Statutom,</li>
                                    <li>Donosi finansijske odluke,</li>
                                    <li>Da podnosi Izveštaj o radu Skupštini jednom godišnje</li>
                                    <li>Odlučuje o pokretanju postupka za izmene i dopune Statuta, sopstvenom inicijativom ili na predlog najmanje pet članova Udruženja i priprema predlog izmena i dopuna, koji podnosi Skupštini na usvajanje,</li>
                                    <li>Donosi Interne akte radi efikasnijeg ostvarivanja ciljeva Udruženja,</li>
                                    <li>Odlučuje o pokretanju postupka za naknadu štete u slučajevima iz člana 25. stav 2. Zakona o udruženjima i, po potrebi, određuje posebnog zastupnika Udruženja za taj postupak,</li>
                                    <li>Odlučuje o počasnom članstvu u Udruženju i izuzetnim nagradama,</li>
                                    <li>Odlučuje o drugim pitanjima za koja nisu, zakonom ili ovim statutom, ovlašćeni drugi organi Udruženja.</li>
                                </ul>
                                <p style="text-align: justify;">Upravni odbor može punopravno da odlučuje ako je prisutna bar polovina članova Upravnog odbora, a o pitanjima iz svoje nadležnosti odlučuje većinom glasova prisutnih članova. U slučaju da je prisutan paran broj članova i da pri glasanju ne postoji većina, glas Predsednika Udruženja ima vrednost dva glasa u glasanju. U slučaju odsustva Predsednika, ovo pravo prenosi se na Podpredsednika i ne može biti preneto na treće lice.</p>
                                <p style="text-align: center;"><strong>&nbsp;Član 18.</strong></p>
                                <p style="text-align: justify;">Nadzorni odbor ima dva člana koje bira Skupština. Mandat članova Nadzornog odbora je 4 godine sa mogućnošću ponovnog izbora bez ograničenja.</p>
                                <p style="text-align: justify;">Nadzorni odbor:</p>
                                <ul>
                                    <li>Kontroliše finansijsko poslovanje udruženja i o uočenim nepravilnostima, bez odlaganja, obaveštava Upravni odbor sa zahtevom da se uočene nepravilnosti otklone,</li>
                                    <li>Podnosi izveštaj na svakoj sednici Skupštine,</li>
                                    <li>Nadzire rad Predsednika kao i ceo Upravni odbor.</li>
                                </ul>
                                <p style="text-align: center;"><strong>Član 19.</strong></p>
                                <p style="text-align: justify;">Predsednik Upravnog odbora predsedava sastancima Upravnog odbora i koordinira njegovim radom, zastupa i predstavlja Udruženje u pravnim i finansijskim poslovima.</p>
                                <p style="text-align: justify;">Zaduženja Članova Upravnog odbora dodeljuje predsednik Upravnog odbora i definiše njihova prava i obaveze u skladu sa ovim Statutom i Internim aktima Udruženja.</p>
                                <p style="text-align: justify;">Funkcije Predsednika i Potpredsednika ne može u isto vreme obavljati jedan član Upravnog Odbora.</p>
                                <p style="text-align: center;"><strong>Član 20.</strong></p>
                                <p style="text-align: justify;">Ovlašćenja za zastupanje i predstavljanje Udruženja poseduju predsednik Upravnog Odbora i Podpredsednik Udruženja. Pravo zastupanja i predstavljanja Udruženja može imati bilo koji član Udruženja.</p>
                                <p style="text-align: justify;">Pravo zastupanja i predstavljanja Udruženja dodeljuje Skupština.</p>
                                <p style="text-align: justify;">Zastupnik Udruženja poseduje sledeća prava:</p>
                                <ul>
                                    <li>Pravo da nastupa u ime Udruženja,</li>
                                    <li>Pravo da zaključuje ugovore u ime Udruženja,</li>
                                    <li>Pravo da koristi pečat Udruženja.</li>
                                </ul>
                                <p style="text-align: justify;">Obim prava Zastupnika Udruženja utvrđuje Upravni odbor Udruženja za svakog pojedinačnog Zastupnika i beleži ih Internim aktima.</p>
                                <p style="text-align: center;"><strong>Član 21.</strong></p>
                                <p style="text-align: justify;">Redovne aktivnosti Udruženja realizuju se kroz Projekte Udruženja.</p>
                                <p style="text-align: center;"><strong>Član 22.</strong></p>
                                <p style="text-align: justify;">U cilju rada na projektima formiraju se posebni timovi. Tim sačinjavaju članovi Udruženja, na način definisan Internim aktima. Tim sačinjavaju minimalno dva člana Udruženja. Formalni predstavnik tima je Koordinator tima.</p>
                                <p style="text-align: center;"><strong>&nbsp;Član 23.</strong></p>
                                <p style="text-align: justify;">Tim ima obavezu da:</p>
                                <ul>
                                    <li>Svojim aktivnostima neposredno doprinosi ostvarenju ciljeva Udruženja</li>
                                    <li>Svojim aktivnostima utiče na razvoj Udruženja kroz razvoj znanja i veština članova Tima, a u skladu sa članom 2 Statuta.</li>
                                </ul>
                                <p style="text-align: center;"><strong>&nbsp;Član 24.</strong></p>
                                <p style="text-align: justify;">Članovi Udruženja koji učestvuju u radu Tima (u daljem tekstu „Članovi tima“) u odnosu na Tim imaju dodatna prava i obaveze.</p>
                                <p style="text-align: justify;">Član tima ima pravo da:</p>
                                <ul>
                                    <li>Bira i bude biran za Koordinatora tima. Izbor se vrši većinom glasova Članova tima.</li>
                                </ul>
                                <p style="text-align: justify;">Član tima ima obaveze da:</p>
                                <ul>
                                    <li>Prisustvuje sastancima Tima,</li>
                                    <li>Učestvuje u aktivnostima Tima u skladu sa svojim mogućnostima i prihvaćenim odgovornostima.</li>
                                </ul>
                                <p style="text-align: center;"><strong>Član 25.</strong></p>
                                <p style="text-align: justify;">Koordinator tima je Član tima izabran većinom glasova Članova tima da predstavlja i vodi Tim u ostvarivanju aktivnosti Tima.</p>
                                <p style="text-align: justify;">Koordinator tima se bira na neodređen vremenski period, odnosno do prestanka rada Tima ili do izbora novog Koordinatora tima. Inicijativu za izbor novog Koordinatora tima može pokrenuti najmanje jedna trećina Članova tima.</p>
                                <p style="text-align: center;"><strong>Član 26.</strong></p>
                                <p style="text-align: justify;">Koordinator tima u odnosu na Tim ima dodatna prava i obaveze.</p>
                                <p style="text-align: justify;">Koordinator tima ima pravo da:</p>
                                <ul>
                                    <li>Primi novog Člana tima u Tim,</li>
                                    <li>Isključi Člana tima iz Tima,</li>
                                    <li>Prisustvuje sastancima Upravnog odbora.</li>
                                </ul>
                                <p style="text-align: justify;">Koordinator tima ima obaveze da:</p>
                                <ul>
                                    <li>Organizuje aktivnosti Tima u skladu sa članom 2 Statuta, a u skladu sa mogućnostima i prihvaćenim odgovornostima Članova tima</li>
                                    <li>Periodično izveštava Upravni odbor o radu Tima kao celine, kao i svih Članova tima ponaosob,</li>
                                    <li>Izveštava Članove tima o odlukama Upravnog odbora koje se direktno ili indirektno odnose na Članove tima,</li>
                                    <li>Predstavlja Tim na redovnim sastancima Udruženja, kao i da pred Skupštinom podnese izveštaj o radu Tima i ostvarenim rezultatima,</li>
                                    <li>Rešava sporove unutar Tima.</li>
                                </ul>
                                <p style="text-align: center;"><strong>Član 27.</strong></p>
                                <p style="text-align: justify;">U slučaju spora unutar Tima ili između Timova, koji nisu regulisani Statutom, nadležni organ za rešavanje spora je Upravni odbor Udruženja.</p>
                                <p style="text-align: center;"><strong>Član 28.</strong></p>
                                <p style="text-align: justify;">Rad Udruženja je javan.</p>
                                <p style="text-align: justify;">Upravni odbor se stara o redovnom obaveštavanju članova i javnosti o radu neposredno ili internim kanalima komunikacije i saopštenjima za javnost.</p>
                                <p style="text-align: center;"><strong>Član 29.</strong></p>
                                <p style="text-align: justify;">Radi ostvarenja ciljeva, Udruženje uspostavlja kontakte i sarađuje sa drugim stručnim, naučnim, obrazovnim i sličnim Udruženjima u zemlji i inostranstvu.</p>
                                <p style="text-align: justify;">Udruženje može pristupiti međunarodnim Udruženjima. Odluku o pristupanju međunarodnim Udruženjima donosi Skupština. Pristupanje pomenutim organizacijama registruje se kod nadležnog državnog organa u roku od 30 dana, u skladu sa zakonom.</p>
                                <p style="text-align: center;"><strong>Član 30.</strong></p>
                                <p style="text-align: justify;">Udruženje se finansira od članarina, donacija, iz kotizacija za seminare i drugih oblasti edukacije,</p>
                                <p style="text-align: justify;">konkurisanjem na tenderima i konkursima za projekte u organizaiji državnih organa ili fondacija i iz drugih izvora, u skladu sa zakonom.</p>
                                <p style="text-align: center;"><strong>Član 31.</strong></p>
                                <p style="text-align: justify;">Udruženje prestaje sa radom odlukom Skupštine, uz pristanak više od dve trećine članova Udruženja, kada prestanu uslovi za ostvarivanje ciljeva Udruženja, kao i u drugim slučajevima predviđenim zakonom.</p>
                                <p style="text-align: justify;">U slučaju prestanka rada Udruženja, imovina Udruženja preneće se na domaće nedobitno pravno lice. Odluku o prenosu imovine Udruženja donosi Skupština.</p>
                                <p style="text-align: center;"><strong>Član 32.</strong></p>
                                <p style="text-align: justify;">Na sva pitanja koja nisu regulisana ovim statutom neposredno će se primenjivati odredbe Zakona o udruženjima.</p>
                                <p style="text-align: right;">Predsedavajući Skupštine Udruženja</p>
                                <p style="text-align: right;"><strong>Nemanja Čedomirović</strong></p>
                                <div class="clear"></div>
                            </div><!--/.entry-->

                        </article>



                    </div><!--/.pad-->

                </section>

                <?= $this->partial('legacy::sidebar'); ?>

            </div><!--/.main-inner-->
        </div><!--/.main-->
    </div><!--/.container-inner-->
</div><!--/.container-->