<form class="form-signin" action="<?php echo $this->url('login'); ?>" method="POST" autocomplete="off">
    <h2 class="text-center"><span class="ks-red">Login to <b>UNFINISHED</b></span></h2>
    <input type="text" autocomplete="on" class="form-control" placeholder="Email address" name="email"><br/>
    <input type="password" autocomplete="on" class="form-control" placeholder="Password" name="password"><br/>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Go Go Go >></button>
</form>