<div class="event-page">
    <div class="headline">
        <div class="headline-container">
            <div class="time-place"><?= date('d M, H', strtotime($event->start_at)) ?>h</div>
            <div class="event-name"><?= $event->title ?></div>
            <div class="instructor-image">
                <img src="<?= $event->main_img ?>" alt="Author">
            </div>
            <div class="instructor-name"><?= $event->place_name ?></div>
            <div class="event-title"><?= $event->sub_title ?></div>
            <a href="#" class="btn btn-blue">Dolaziš?</a>
        </div>
    </div>

    <div class="event-single-wrapper">
        <div class="social-share">
            <div class="social-icons social-icon__vertical">
                <div class="social-icon-shared">
                    <strong>142</strong>
                    <span>Podeljeno</span>
                </div>
                <a href="#" target="_blank">
                    <button class="btn btn-white social icon-facebook"></button>
                </a>
                <a href="#" target="_blank">
                    <button class="btn btn-white social icon-twitter"></button>
                </a>
                <a href="#" target="_blank">
                    <button class="btn btn-white social icon-linkedin"></button>
                </a>
            </div>
        </div>
        <div class="event-text">
            <?= $event->body ?>

            <!--
            <div class="show-more">
                <a class="btn btn-white btn-block" href="#">Ostavite komentar</a>
            </div>
            -->
        </div>

        <div class="event-description">
            <iframe frameborder="0" style="border:0" allowfullscreen
                    src="https://maps.google.com/maps?q=<?= $event->latitude ?>,<?= $event->longitude ?>&hl=es;z=14&amp;output=embed"></iframe>


            <ul class="list-users">
                <li>
                    <div class="user-img">
                        <img src="/images/event/instructor.jpg" alt="User image">
                    </div>
                    <strong>PHP Srbija</strong> Organizer, Event Host
                </li>
                <li>
                    <div class="user-img">
                        <img src="/images/event/instructor.jpg" alt="User image">
                    </div>
                    <strong>Vladeta Radovanovic</strong> Organizer, Event Host
                </li>
                <li>
                    <div class="user-img">
                        <img src="/images/event/instructor.jpg" alt="User image">
                    </div>
                    <strong>PHP Srbija</strong> Organizer, Event Host
                </li>
                <li>
                    <div class="user-img">
                        <img src="/images/event/instructor.jpg" alt="User image">
                    </div>
                    <strong>PHP Srbija</strong> Organizer, Event Host
                </li>
                <li>
                    <div class="user-img">
                        <img src="/images/event/instructor.jpg" alt="User image">
                    </div>
                    <strong>PHP Srbija</strong> Organizer, Event Host
                </li>
            </ul>
            <a href="#" class="load-more-link">Ucitaj jos</a>

        </div>
    </div>
</div>

<!--
<div class="half-pagination">
    <div class="paginate-prev">
        <a href="#">
            <small>Prethodni članak</small>
            <div class="title">True North PHP 2016 ReviewŁ</div>
        </a>
    </div>
    <div class="paginate-next">
        <a href="#">
            <small>Sledeći članak</small>
            <div class="title">Drugo okupljanje PHP programera u Nišu</div>
        </a>
    </div>
</div>
-->