<?php
$event   = $futureEvents->count() ? $futureEvents->current() : $pastEvents->getItem(0);
$escaper = (new \Zend\Escaper\Escaper);
$this->headTitle($escaper->escapeHtml($event->title));
$this->headMeta($escaper->escapeHtml($event->sub_title), 'description');
?>

<div class="event-page">
    <div class="headline">
        <div class="headline-container">
            <div class="time-place"><?= date('d M, H', strtotime($event->start_at)) ?>h</div>
            <div class="event-name"><?= $event->title ?></div>
            <div class="instructor-image">
                <img src="<?= $event->main_img ?>" alt="Author">
            </div>
            <div class="instructor-name"><?= $event->place_name ?></div>
            <div class="event-title"><?= $event->sub_title ?></div>
            <a href="<?= $this->url('event', ['event_slug' => $event->slug]) ?>" class="btn btn-blue">Dolaziš?</a>
        </div>
    </div>
    <ul class="event-tags-wrapper">
        <!--
        <li><a class="link tag" href="#">Sve</a></li>
        <li><a class="link tag" href="#">Konferencija</a></li>
        <li><a class="link tag" href="#">Meetup</a></li>
        -->
    </ul>

    <div class="event-wrapper">
        <?php if($futureEvents->count() > 1): ?>
            <div class="event-status-title">Naredna dešavanja</div>
        <?php endif; ?>

        <div class="event-mid-wrapper">
            <?php foreach($futureEvents as $event): ?>
                <a href="<?= $this->url('event', ['event_slug' => $event->slug]) ?>" class="event"
                   data-title="<?= $event->title ?>"
                   data-image="<?= 'http://' . $_SERVER['HTTP_HOST'] . $event->main_img ?>">
                    <div class="image-wrapper-none image-transition">
                        <img src="<?= $event->main_img ?>">

                        <div class="date-outer-wrapper">
                            <div class="headline">Datum</div>
                            <div class="date-inner-wrapper">
                                <div class="date"><?= date('d', strtotime($event->start_at)) ?></div>
                                <div class="month"><?= date('M', strtotime($event->start_at)) ?></div>
                            </div>
                        </div>
                        <button class="btn btn-share facebook-share-list">PODELI</button>
                        <div class="event-box-hover"></div>
                    </div>
                    <div class="event-box-content">
                        <div class="time-place">
                            <span><?= date('H', strtotime($event->start_at)) ?>h</span>@
                            <span><?= $event->place_name ?></span>
                        </div>
                        <div class="title"><?= $event->sub_title ?></div>
                        <div class="details"></div>
                        <div class="author">PHP Srbija</div>
                    </div>
                </a>
            <?php endforeach; ?>
            <div class="event-be-instructor">
                <a href="/vesti/uskoro">
                    <img src="/images/event/be-instructor.jpg" alt="Prijavi se kao predavac">
                </a>
            </div>
        </div>
        <div class="event-finished">
            <div class="event-status-title">Prethodna dešavanja</div>
            <div class="event-mid-wrapper">
                <?php foreach($pastEvents as $event): ?>
                    <a href="<?= $this->url('event', ['event_slug' => $event->slug]) ?>" class="event"
                       data-title="<?= $event->title ?>"
                       data-image="<?= 'http://' . $_SERVER['HTTP_HOST'] . $event->main_img ?>">
                        <div class="image-wrapper-none image-transition">
                            <img src="<?= $event->main_img ?>"/>

                            <div class="date-outer-wrapper">
                                <div class="headline">Datum</div>
                                <div class="date-inner-wrapper">
                                    <div class="date"><?= date('d', strtotime($event->start_at)) ?></div>
                                    <div class="month"><?= date('M', strtotime($event->start_at)) ?></div>
                                </div>
                            </div>
                            <button class="btn btn-share facebook-share-list">PODELI</button>
                            <div class="event-box-hover"></div>
                        </div>
                        <div class="event-box-content">
                            <div class="time-place">
                                <span><?= date('H', strtotime($event->start_at)) ?>h</span>@
                                <span><?= $event->place_name ?></span>
                            </div>
                            <div class="title"><?= $event->sub_title ?></div>
                            <div class="details"></div>
                            <div class="author">PHP Srbija</div>
                        </div>
                    </a>
                <?php endforeach; ?>
            </div>
            <br/>
        </div>
    </div>
</div>
<div class="half-pagination">
    <?= $this->paginationControl($pastEvents, 'Sliding', 'article/pagination', ['route' => 'events']) ?>
</div>