<!-- First Event -->
<a href="#" class="link active-news">
    <div class="active-news-box" data-mobile-active-src="" data-tablet-active-src="" data-desktop-active-src="">
        <img class="active-news-box-mask" src="/images/news-mask.png">
    </div>
    <div class="active-news-box-content">
        <div class="title"></div>
        <div class="details"></div>
        <div class="author"></div>
    </div>
</a>
<!-- \First Event -->

<!-- Latest 4 Events -->
<div class="news-wrapper">
    <?php foreach($this->event()->getLatest() as $count => $event): ?>
        <a href="#" class="link news <?= $count == 0 ? 'selected' : '' ?>"
           data-mobile-src="<?= $event->featured_img ?>"
           data-tablet-src="<?= $event->featured_img ?>"
           data-desktop-src="<?= $event->featured_img ?>">
            <div class="image-wrapper">
                <img src="<?= $event->main_img ?>">
                <div class="date-outer-wrapper">
                    <div class="headline">MEETUP</div>
                    <div class="date-inner-wrapper">
                        <div class="date"><?= date("d", strtotime($event->start_at)); ?></div>
                        <div class="month"><?= date("F", strtotime($event->start_at)); ?></div>
                    </div>
                </div>
                <button class="btn btn-share">PODELI</button>
                <div class="news-box-hover"></div>
            </div>
            <div class="news-box-content">
                <div class="time-place">
                    <span><?= date("h", strtotime($event->start_at)); ?>h</span>@
                    <span><?= $event->place_name ?></span>
                </div>
                <div class="title"><?= $event->title ?></div>
                <div class="details"></div>
                <div class="author">PHP Srbija</div>
            </div>
        </a>
    <?php endforeach; ?>
</div>
<!-- \Latest 4 Events -->

<div class="forum">
    <div class="headline">Poslednje sa foruma</div>
    <ul class="tags-wrapper">
        <?php foreach($this->category()->forWeb() as $category): ?>
            <li><a class="link tag" href="#"><?= strtolower($category['name']) ?></a></li>
        <?php endforeach; ?>
    </ul>
    <div class="forum-box-wrapper">
        <?php foreach($this->category()->forWeb() as $category): ?>
            <?php foreach($category['posts'] as $post): ?>
                <div class="forum-box" data-active-tag="<?= strtolower($category['name']) ?>">
                    <a href="#" class="image-wrapper">
                        <img src="/images/forum/1.jpg">
                        <div class="name"><?= $post['first_name'] . ' ' . $post['last_name'] ?></div>
                    </a>
                    <div class="question-wrapper">
                        <a href="#" class="question"><?= $post['title'] ?></a>
                        <div class="tag">
                            <?= $category['name'] ?>
                            <span class="circle">●</span>
                            <span class="posted"><?= date('d.m.y H:i', strtotime($post['published_at'])) ?>h</span>
                        </div>
                        <div class="comment-wrapper">
                            <a href="#">Komentariši</a>
                        </div>
                    </div>
                    <div class="response-wrapper active">
                        <div class="response-number">0</div>
                        <div class="response-text">odgovora</div>
                    </div>
                </div>
            <?php endforeach; ?>
        <?php endforeach; ?>

        <div class="show-more">
            <a class="btn btn-white" data-history data-ajax="/forum-1.html" href="/forum/2">UČITAJ JOŠ SA FORUMA</a>
        </div>
    </div>
</div>

<!-- Video section -->
<div class="videos">
    <div class="slider-video-wrapper">
        <div class="headline">Video Materijali</div>
        <div class="slider slider-video">
            <?php foreach($this->video()->getLatest() as $video): ?>
                <div class="video-slide">
                    <div class="video-wrapper">
                        <video poster="<?= $video->main_img ?>">
                            <source src="/videos/test.mp4" type="video/mp4">
                        </video>
                        <div class="slider-video-hover-box"></div>
                        <div class="video-content-wrapper">
                            <div class="title"><?= $video->title ?></div>
                            <div class="description"><?= $video->lead ?></div>
                            <button class="btn btn-play icon-play"></button>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
        <a class="link video" href="/php-videos/">Pogledaj sve video zapise</a>
    </div>
    <div class="slider slider-thumbnail">
        <?php foreach($this->video()->getLatest() as $video): ?>
            <div class="video-slide">
                <div class="video-wrapper">
                    <video poster="<?= $video->main_img ?>">
                        <source src="/videos/test.mp4" type="video/mp4">
                    </video>
                    <div class="slider-video-hover-box"></div>
                    <div class="video-content-wrapper">
                        <div class="title"><?= $video->title ?></div>
                        <div class="description"><?= $video->lead ?></div>
                        <button class="btn btn-play icon-play"></button>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>
<!-- \Video section -->

<div class="posts">
    <div class="headline">Ostali Članci & Aktuelnosti</div>
    <article class="post-box main">
        <div class="image-wrapper" data-desktop-active-src="/images/posts/main.jpg">
            <img src="/images/posts/main.jpg">
            <div class="post-box-hover"></div>
        </div>
        <div class="post-box-content">
            <div class="section">Anketa</div>
            <a href="#" class="title"><span>Rezultati ankete „Žene i devojke u IT svetu“</span></a>
            <a href="#" class="author">PHP Srbija</a>
        </div>
    </article>

    <article class="post-box">
        <div class="image-wrapper" data-desktop-active-src="/images/posts/1.jpg">
            <img src="/images/posts/1.jpg">
            <div class="post-box-hover"></div>
        </div>
        <div class="post-box-content">
            <div class="section">Utisci sa Konferencije</div>
            <a href="#" class="title"><span>True North PHP 2016 Review and much more...</span></a>
            <a href="#" class="author">PHP Srbija</a>
        </div>
    </article>

    <article class="post-box">
        <div class="image-wrapper" data-desktop-active-src="/images/posts/2.jpg">
            <img src="/images/posts/2.jpg">
            <div class="post-box-hover"></div>
        </div>
        <div class="post-box-content">
            <div class="section">Izveštaj</div>
            <a href="#" class="title"><span>Kreator- PHP-a dolazi u Beograd</span></a>
            <a href="#" class="author">PHP Srbija</a>
        </div>
    </article>

    <article class="post-box">
        <div class="image-wrapper" data-desktop-active-src="/images/posts/3.jpg">
            <img src="/images/posts/3.jpg">
            <div class="post-box-hover"></div>
        </div>
        <div class="post-box-content">
            <div class="section">Anketa</div>
            <a href="#" class="title"><span>Prva „Agile Serbia Konferencija“</span></a>
            <a href="#" class="author">PHP Srbija</a>
        </div>
    </article>

    <article class="post-box">
        <div class="image-wrapper" data-desktop-active-src="/images/posts/4.jpg">
            <img src="/images/posts/4.jpg">
            <div class="post-box-hover"></div>
        </div>
        <div class="post-box-content">
            <div class="section">Utisci sa Konferencije</div>
            <a href="#" class="title"><span>Kreator- PHP-a dolazi u Beograd</span></a>
            <a href="#" class="author">PHP Srbija</a>
        </div>
    </article>

    <article class="post-box">
        <div class="image-wrapper" data-desktop-active-src="/images/posts/5.jpg">
            <img src="/images/posts/5.jpg">
            <div class="post-box-hover"></div>
        </div>
        <div class="post-box-content">
            <div class="section">Izveštaj</div>
            <a href="#" class="title"><span>Prva „Agile Serbia Konferencija u Beogradu“</span></a>
            <a href="#" class="author">PHP Srbija</a>
        </div>
    </article>

    <article class="post-box">
        <div class="image-wrapper" data-desktop-active-src="/images/posts/6.jpg">
            <img src="/images/posts/6.jpg">
            <div class="post-box-hover"></div>
        </div>
        <div class="post-box-content">
            <div class="section">Anketa</div>
            <a href="#" class="title"><span>True North PHP 2016 Review</span></a>
            <a href="#" class="author">PHP Srbija</a>
        </div>
    </article>
</div>

<div class="social-network">
    <div class="headline">Pratite nas i koristite <a href="#">#PHPSrbija</a></div>
    <div class="social-icons">
        <a href="#" target="_blank">
            <button class="btn btn-white social icon-facebook"></button>
        </a>
        <a href="#" target="_blank">
            <button class="btn btn-white social icon-twitter"></button>
        </a>
        <a href="#" target="_blank">
            <button class="btn btn-white social instagram">
		        <span class="icon-instagram">
		            <span class="path1"></span>
		            <span class="path2"></span>
		            <span class="path3"></span>
		            <span class="path4"></span>
		        </span>
            </button>
        </a>
        <a href="#" target="_blank">
            <button class="btn btn-white social icon-linkedin"></button>
        </a>
    </div>
    <div class="slider slider-social">
        <div class="social-slide">
            <a href="#" class="image-wrapper">
                <img src="/images/social/1.jpg">
            </a>
        </div>
        <div class="social-slide">
            <div class="text-wrapper">
                <p>
                    Četvrti PHP Conference krajem maja u Beogradu – zajedno sa osnivačem PHP-a!
                    <a href="#">http://buff.ly/2m7Tx6B</a> cc <a href="#">@PHPSrbija</a>
                </p>
            </div>
        </div>
        <div class="social-slide">
            <a href="#" class="image-wrapper">
                <img src="/images/social/2.jpg">
            </a>
        </div>
        <div class="social-slide">
            <div class="text-wrapper">
                <p>
                    We are so proud to have Pirate Technologies as our Gold sponsor for the second year in a row!
                    <a href="#">http://conf2017.phpsrbija.rs/</a> <a href="#">#phpsrb17</a>
                </p>
            </div>
        </div>
        <div class="social-slide">
            <div class="text-wrapper">
                <p>Presenting our Gold sponsor - Quantox Technology <a
                            href="#">http://www.conf2017.phpsrbija.rs/post/9</a> <a href="#">#phpsrb17</a></p>
            </div>
        </div>
        <div class="social-slide">
            <a href="#" class="image-wrapper">
                <img src="/images/social/1.jpg">
            </a>
        </div>
        <div class="social-slide">
            <div class="text-wrapper">
                <p>Presenting our Gold sponsor - Quantox Technology <a
                            href="#">http://www.conf2017.phpsrbija.rs/post/9</a> <a href="#">#phpsrb17</a></p>
            </div>
        </div>
        <div class="social-slide">
            <a href="#" class="image-wrapper">
                <img src="/images/social/1.jpg">
            </a>
        </div>
    </div>
</div>

<div class="society">
    <div class="intro">
        <div class="meet">Upoznajte članove udruženja</div>
        <a class="link reload icon-reload" href="#"></a>
    </div>
    <div class="members">
        <article>
            <img src="/images/members/1.jpg">
            <div class="hover-box">
                <div class="center-box">
                    <div class="inner-box y-centered">
                        <p class="name">Nemanja Čedomirović</p>
                        <p class="title">Jedan od osnivača Udruženja PHP Srbija.</p>
                    </div>
                </div>
                <button class="btn btn-link icon-close"></button>
            </div>

        </article>
        <article>
            <img src="/images/members/2.jpg">
            <div class="hover-box">
                <div class="center-box">
                    <div class="inner-box y-centered">
                        <p class="name">Nemanja Čedomirović</p>
                        <p class="title">Jedan od osnivača Udruženja PHP Srbija.</p>
                    </div>
                </div>
                <button class="btn btn-link icon-close"></button>
            </div>

        </article>
        <article>
            <img src="/images/members/3.jpg">
            <div class="hover-box">
                <div class="center-box">
                    <div class="inner-box y-centered">
                        <p class="name">Nemanja Čedomirović</p>
                        <p class="title">Jedan od osnivača Udruženja PHP Srbija.</p>
                    </div>
                </div>
                <button class="btn btn-link icon-close"></button>
            </div>

        </article>
        <article>
            <img src="/images/members/4.jpg">
            <div class="hover-box">
                <div class="center-box">
                    <div class="inner-box y-centered">
                        <p class="name">Nemanja Čedomirović</p>
                        <p class="title">Jedan od osnivača Udruženja PHP Srbija.</p>
                    </div>
                </div>
                <button class="btn btn-link icon-close"></button>
            </div>

        </article>
        <article>
            <img src="/images/members/5.jpg">
            <div class="hover-box">
                <div class="center-box">
                    <div class="inner-box y-centered">
                        <p class="name">Nemanja Čedomirović</p>
                        <p class="title">Jedan od osnivača Udruženja PHP Srbija.</p>
                    </div>
                </div>
                <button class="btn btn-link icon-close"></button>
            </div>

        </article>
        <article class="add">
            <a class="link abs-wrapper" href="#">
                <div class="center">
                    <div class="add-user"></div>
                    <div class="you">PRIKLJUČI SE I TI</div>
                </div>
            </a>
        </article>
    </div>
</div>