<a href="#" class="link active-news">
    <div class="active-news-box" data-mobile-active-src="" data-tablet-active-src="" data-desktop-active-src="">
        <img class="active-news-box-mask" src="/images/news-mask.png">
    </div>
    <div class="active-news-box-content">
        <div class="title"></div>
        <div class="details"></div>
        <div class="author"></div>
    </div>
</a>
<div class="news-wrapper">
    <a href="#" class="link news selected"
       data-mobile-src="/images/news/1/mobile.jpg"
       data-tablet-src="/images/news/1/tablet.jpg"
       data-desktop-src="/images/news/1/desktop.jpg">

        <div class="image-wrapper">
            <img src="/images/news/1/thumbnail.jpg">
            <div class="date-outer-wrapper">
                <div class="headline">MEETUP</div>
                <div class="date-inner-wrapper">
                    <div class="date">10</div>
                    <div class="month">MAR</div>
                </div>
            </div>
            <button class="btn btn-share">PODELI</button>
            <div class="news-box-hover"></div>
        </div>
        <div class="news-box-content">
            <div class="time-place"><span>19h</span>@<span>KC Grad</span></div>
            <div class="title">Pozivamo vas na poslednji PHP Srbija Meetup u ovoj godini. ☺</div>
            <div class="details"></div>
            <div class="author">PHP Srbija</div>
        </div>
    </a>

    <a href="#" class="link news"
       data-mobile-src="/images/news/2/mobile.jpg"
       data-tablet-src="/images/news/2/tablet.jpg"
       data-desktop-src="/images/news/2/desktop.jpg">

        <div class="image-wrapper">
            <img src="/images/news/2/thumbnail.jpg">
            <div class="date-outer-wrapper">
                <div class="headline">WORKSHOP</div>
                <div class="date-inner-wrapper">
                    <div class="date">15</div>
                    <div class="month">apr</div>
                </div>
            </div>
            <button class="btn btn-share">PODELI</button>
            <div class="news-box-hover"></div>
        </div>
        <div class="news-box-content">
            <div class="time-place"><span>19h</span>@<span>KC Grad</span></div>
            <div class="title">PHP Srbija Conference 2017</div>
            <div class="details">Najveća regionalna PHP konferencija</div>
            <div class="author">PHP Srbija</div>
        </div>
    </a>

    <a href="#" class="link news"
       data-mobile-src="/images/news/3/mobile.jpg"
       data-tablet-src="/images/news/3/tablet.jpg"
       data-desktop-src="/images/news/3/desktop.jpg">

        <div class="image-wrapper">
            <img src="/images/news/3/thumbnail.jpg">
            <div class="date-outer-wrapper">
                <div class="headline">MEETUP</div>
                <div class="date-inner-wrapper">
                    <div class="date">10</div>
                    <div class="month">MAR</div>
                </div>
            </div>
            <button class="btn btn-share">PODELI</button>
            <div class="news-box-hover"></div>
        </div>
        <div class="news-box-content">
            <div class="time-place"><span>19h</span>@<span>KC Grad</span></div>
            <div class="title">ITkonekt – najveći online IT događaj u regionu</div>
            <div class="details"></div>
            <div class="author">PHP Srbija</div>
        </div>
    </a>

    <a href="#" class="link news"
       data-mobile-src="/images/news/4/mobile.jpg"
       data-tablet-src="/images/news/4/tablet.jpg"
       data-desktop-src="/images/news/4/desktop.jpg">

        <div class="image-wrapper">
            <img src="/images/news/4/thumbnail.jpg">
            <div class="date-outer-wrapper">
                <div class="headline">CONFERENCE</div>
                <div class="date-inner-wrapper">
                    <div class="date">20</div>
                    <div class="month">MAY</div>
                </div>
            </div>
            <button class="btn btn-share">PODELI</button>
            <div class="news-box-hover"></div>
        </div>
        <div class="news-box-content">
            <div class="time-place"><span>19h</span>@<span>KC Grad</span></div>
            <div class="title">ITkonekt – najveći online IT događaj u regionu</div>
            <div class="details"></div>
            <div class="author">PHP Srbija</div>
        </div>
    </a>
</div>

<div class="forum">
    <div class="headline">Poslednje sa Foruma</div>
    <ul class="tags-wrapper">
        <li><a class="link tag" href="#">frameworks</a></li>
        <li><a class="link tag" href="#">magento</a></li>
        <li><a class="link tag" href="#">php mvc</a></li>
        <li><a class="link tag" href="#">design patterns</a></li>
    </ul>
    <div class="forum-box-wrapper">
        <div class="forum-box" data-active-tag="frameworks">
            <a href="#" class="image-wrapper">
                <img src="/images/forum/1.jpg">
                <div class="name">Ivan Ilić</div>
            </a>
            <div class="question-wrapper">
                <a href="#" class="question">Koji framework preporučujete za početak?</a>
                <div class="tag">FRAMEWORKS<span class="circle">●</span><span class="posted">Pre 9 minuta</span></div>
                <div class="comment-wrapper">
                    <a href="#">Komentariši</a>
                </div>
            </div>
            <div class="response-wrapper active">
                <div class="response-number">8</div>
                <div class="response-text">odgovora</div>
            </div>
        </div>

        <div class="forum-box" data-active-tag="magento">
            <a href="#" class="image-wrapper">
                <img src="/images/forum/1.jpg">
                <div class="name">Marko Nikolić</div>
            </a>
            <div class="question-wrapper">
                <a href="#" class="question">Koji framework preporučujete za početak?</a>
                <div class="tag">MAGENTO<span class="circle">●</span><span class="posted">Pre 9 minuta</span></div>
                <div class="comment-wrapper">
                    <a href="#">Komentariši</a>
                </div>
            </div>
            <div class="response-wrapper">
                <div class="response-number">8</div>
                <div class="response-text">odgovora</div>
            </div>
        </div>

        <div class="forum-box" data-active-tag="php mvc">
            <a href="#" class="image-wrapper">
                <img src="/images/forum/1.jpg">
                <div class="name">Aca Nesović</div>
            </a>
            <div class="question-wrapper">
                <a href="#" class="question">Koji framework preporučujete za početak?</a>
                <div class="tag">PHP MVC<span class="circle">●</span><span class="posted">Pre 9 minuta</span></div>
                <div class="comment-wrapper">
                    <a href="#">Komentariši</a>
                </div>
            </div>
            <div class="response-wrapper">
                <div class="response-number">8</div>
                <div class="response-text">odgovora</div>
            </div>


        </div>

        <div class="forum-box" data-active-tag="frameworks">
            <a href="#" class="image-wrapper">
                <img src="/images/forum/1.jpg">
                <div class="name">Ivan Ilić</div>
            </a>
            <div class="question-wrapper">
                <a href="#" class="question">Koji framework preporučujete za početak?</a>
                <div class="tag">FRAMEWORKS<span class="circle">●</span><span class="posted">Pre 9 minuta</span></div>
                <div class="comment-wrapper">
                    <a href="#">Komentariši</a>
                </div>
            </div>
            <div class="response-wrapper">
                <div class="response-number">8</div>
                <div class="response-text">odgovora</div>
            </div>
        </div>

        <div class="forum-box" data-active-tag="magento">
            <a href="#" class="image-wrapper">
                <img src="/images/forum/1.jpg">
                <div class="name">Marko Nikolić</div>
            </a>
            <div class="question-wrapper">
                <a href="#" class="question">Koji framework preporučujete za početak?</a>
                <div class="tag">MAGENTO<span class="circle">●</span><span class="posted">Pre 9 minuta</span></div>
                <div class="comment-wrapper">
                    <a href="#">Komentariši</a>
                </div>
            </div>
            <div class="response-wrapper active">
                <div class="response-number">8</div>
                <div class="response-text">odgovora</div>
            </div>
        </div>
        <div class="forum-box" data-active-tag="php mvc">
            <a href="#" class="image-wrapper">
                <img src="/images/forum/1.jpg">
                <div class="name">Aca Nesović</div>
            </a>
            <div class="question-wrapper">
                <a href="#" class="question">Koji framework preporučujete za početak?</a>
                <div class="tag">PHP MVC<span class="circle">●</span><span class="posted">Pre 9 minuta</span></div>
                <div class="comment-wrapper">
                    <a href="#">Komentariši</a>
                </div>
            </div>
            <div class="response-wrapper">
                <div class="response-number">8</div>
                <div class="response-text">odgovora</div>
            </div>
        </div>

        <div class="forum-box" data-active-tag="frameworks">
            <a href="#" class="image-wrapper">
                <img src="/images/forum/1.jpg">
                <div class="name">Ivan Ilić</div>
            </a>
            <div class="question-wrapper">
                <a href="#" class="question">Koji framework preporučujete za početak?</a>
                <div class="tag">FRAMEWORKS<span class="circle">●</span><span class="posted">Pre 9 minuta</span></div>
                <div class="comment-wrapper">
                    <a href="#">Komentariši</a>
                </div>
            </div>
            <div class="response-wrapper">
                <div class="response-number">8</div>
                <div class="response-text">odgovora</div>
            </div>
        </div>

        <div class="forum-box" data-active-tag="magento">
            <a href="#" class="image-wrapper">
                <img src="/images/forum/1.jpg">
                <div class="name">Marko Nikolić</div>
            </a>
            <div class="question-wrapper">
                <a href="#" class="question">Koji framework preporučujete za početak?</a>
                <div class="tag">MAGENTO<span class="circle">●</span><span class="posted">Pre 9 minuta</span></div>
                <div class="comment-wrapper">
                    <a href="#">Komentariši</a>
                </div>
            </div>
            <div class="response-wrapper">
                <div class="response-number">8</div>
                <div class="response-text">odgovora</div>
            </div>
        </div>
        <div class="forum-box" data-active-tag="php mvc">
            <a href="#" class="image-wrapper">
                <img src="/images/forum/1.jpg">
                <div class="name">Aca Nesović</div>
            </a>
            <div class="question-wrapper">
                <a href="#" class="question">Koji framework preporučujete za početak?</a>
                <div class="tag">PHP MVC<span class="circle">●</span><span class="posted">Pre 9 minuta</span></div>
                <div class="comment-wrapper">
                    <a href="#">Komentariši</a>
                </div>
            </div>
            <div class="response-wrapper active">
                <div class="response-number">8</div>
                <div class="response-text">odgovora</div>
            </div>
        </div>
        <div class="show-more">
            <a class="btn btn-white" data-history data-ajax="/forum-1.html" href="/forum/2">UČITAJ JOŠ SA FORUMA</a>
        </div>
    </div>
</div>

<div class="videos">
    <div class="slider-video-wrapper">
        <div class="headline">Video Materijali</div>
        <div class="slider slider-video">
            <div class="video-slide">
                <div class="video-wrapper">
                    <video poster="/images/videos/placeholder.jpg">
                        <source src="/videos/test.mp4" type="video/mp4">
                    </video>
                    <div class="slider-video-hover-box"></div>
                    <div class="video-content-wrapper">
                        <div class="title">Propustili ste mesečni meetup #1?</div>
                        <div class="description">Quo Vadis? - Srđan Vranac</div>
                        <button class="btn btn-play icon-play"></button>
                    </div>
                </div>
            </div>

            <div class="video-slide">
                <div class="video-wrapper">
                    <video poster="/images/videos/placeholder2.jpg">
                        <source src="/videos/test.mp4" type="video/mp4">
                    </video>
                    <div class="slider-video-hover-box"></div>
                    <div class="video-content-wrapper">
                        <div class="title">Propustili ste mesečni meetup #2?</div>
                        <div class="description">Quo Vadis? - Srđan Vranac</div>
                        <button class="btn btn-play icon-play"></button>
                    </div>
                </div>
            </div>

            <div class="video-slide">
                <div class="video-wrapper">
                    <video poster="/images/videos/placeholder.jpg">
                        <source src="/videos/test.mp4" type="video/mp4">
                    </video>
                    <div class="slider-video-hover-box"></div>
                    <div class="video-content-wrapper">
                        <div class="title">Propustili ste mesečni meetup #3?</div>
                        <div class="description">Quo Vadis? - Srđan Vranac</div>
                        <button class="btn btn-play icon-play"></button>
                    </div>
                </div>
            </div>

            <div class="video-slide">
                <div class="video-wrapper">
                    <video poster="/images/videos/placeholder2.jpg">
                        <source src="/videos/test.mp4" type="video/mp4">
                    </video>
                    <div class="slider-video-hover-box"></div>
                    <div class="video-content-wrapper">
                        <div class="title">Propustili ste mesečni meetup #4?</div>
                        <div class="description">Quo Vadis? - Srđan Vranac</div>
                        <button class="btn btn-play icon-play"></button>
                    </div>
                </div>
            </div>


        </div>
        <a class="link video" href="#">Pogledaj sve video zapise</a>
    </div>
    <div class="slider slider-thumbnail">
        <div class="video-slide">
            <div class="video-wrapper">
                <video poster="/images/videos/placeholder.jpg">
                    <source src="/videos/test.mp4" type="video/mp4">
                </video>
                <div class="slider-video-hover-box"></div>
                <div class="video-content-wrapper">
                    <div class="title">@@title</div>
                    <div class="description">@@description</div>
                    <button class="btn btn-play icon-play"></button>
                </div>
            </div>
        </div>

        <div class="video-slide">
            <div class="video-wrapper">
                <video poster="/images/videos/placeholder2.jpg">
                    <source src="/videos/test.mp4" type="video/mp4">
                </video>
                <div class="slider-video-hover-box"></div>
                <div class="video-content-wrapper">
                    <div class="title">@@title</div>
                    <div class="description">@@description</div>
                    <button class="btn btn-play icon-play"></button>
                </div>
            </div>
        </div>

        <div class="video-slide">
            <div class="video-wrapper">
                <video poster="/images/videos/placeholder.jpg">
                    <source src="/videos/test.mp4" type="video/mp4">
                </video>
                <div class="slider-video-hover-box"></div>
                <div class="video-content-wrapper">
                    <div class="title">@@title</div>
                    <div class="description">@@description</div>
                    <button class="btn btn-play icon-play"></button>
                </div>
            </div>
        </div>

        <div class="video-slide">
            <div class="video-wrapper">
                <video poster="/images/videos/placeholder2.jpg">
                    <source src="/videos/test.mp4" type="video/mp4">
                </video>
                <div class="slider-video-hover-box"></div>
                <div class="video-content-wrapper">
                    <div class="title">@@title</div>
                    <div class="description">@@description</div>
                    <button class="btn btn-play icon-play"></button>
                </div>
            </div>
        </div>

    </div>
</div>


<div class="posts">
    <div class="headline">Ostali Članci & Aktuelnosti</div>
    <article class="post-box main">
        <div class="image-wrapper" data-desktop-active-src="/images/posts/main.jpg">
            <img src="/images/posts/main.jpg">
            <div class="post-box-hover"></div>
        </div>
        <div class="post-box-content">
            <div class="section">Anketa</div>
            <a href="#" class="title"><span>Rezultati ankete „Žene i devojke u IT svetu“</span></a>
            <a href="#" class="author">PHP Srbija</a>
        </div>
    </article>

    <article class="post-box">
        <div class="image-wrapper" data-desktop-active-src="/images/posts/1.jpg">
            <img src="/images/posts/1.jpg">
            <div class="post-box-hover"></div>
        </div>
        <div class="post-box-content">
            <div class="section">Utisci sa Konferencije</div>
            <a href="#" class="title"><span>True North PHP 2016 Review and much more...</span></a>
            <a href="#" class="author">PHP Srbija</a>
        </div>
    </article>

    <article class="post-box">
        <div class="image-wrapper" data-desktop-active-src="/images/posts/2.jpg">
            <img src="/images/posts/2.jpg">
            <div class="post-box-hover"></div>
        </div>
        <div class="post-box-content">
            <div class="section">Izveštaj</div>
            <a href="#" class="title"><span>Kreator- PHP-a dolazi u Beograd</span></a>
            <a href="#" class="author">PHP Srbija</a>
        </div>
    </article>

    <article class="post-box">
        <div class="image-wrapper" data-desktop-active-src="/images/posts/3.jpg">
            <img src="/images/posts/3.jpg">
            <div class="post-box-hover"></div>
        </div>
        <div class="post-box-content">
            <div class="section">Anketa</div>
            <a href="#" class="title"><span>Prva „Agile Serbia Konferencija“</span></a>
            <a href="#" class="author">PHP Srbija</a>
        </div>
    </article>

    <article class="post-box">
        <div class="image-wrapper" data-desktop-active-src="/images/posts/4.jpg">
            <img src="/images/posts/4.jpg">
            <div class="post-box-hover"></div>
        </div>
        <div class="post-box-content">
            <div class="section">Utisci sa Konferencije</div>
            <a href="#" class="title"><span>Kreator- PHP-a dolazi u Beograd</span></a>
            <a href="#" class="author">PHP Srbija</a>
        </div>
    </article>

    <article class="post-box">
        <div class="image-wrapper" data-desktop-active-src="/images/posts/5.jpg">
            <img src="/images/posts/5.jpg">
            <div class="post-box-hover"></div>
        </div>
        <div class="post-box-content">
            <div class="section">Izveštaj</div>
            <a href="#" class="title"><span>Prva „Agile Serbia Konferencija u Beogradu“</span></a>
            <a href="#" class="author">PHP Srbija</a>
        </div>
    </article>

    <article class="post-box">
        <div class="image-wrapper" data-desktop-active-src="/images/posts/6.jpg">
            <img src="/images/posts/6.jpg">
            <div class="post-box-hover"></div>
        </div>
        <div class="post-box-content">
            <div class="section">Anketa</div>
            <a href="#" class="title"><span>True North PHP 2016 Review</span></a>
            <a href="#" class="author">PHP Srbija</a>
        </div>
    </article>
</div>

<div class="social-network">
    <div class="headline">Pratite nas i koristite <a href="#">#PHPSrbija</a></div>
    <div class="social-icons">
        <a href="#" target="_blank">
            <button class="btn btn-white social icon-facebook"></button>
        </a>
        <a href="#" target="_blank">
            <button class="btn btn-white social icon-twitter"></button>
        </a>
        <a href="#" target="_blank">
            <button class="btn btn-white social instagram">
		        <span class="icon-instagram">
		            <span class="path1"></span>
		            <span class="path2"></span>
		            <span class="path3"></span>
		            <span class="path4"></span>
		        </span>
            </button>
        </a>
        <a href="#" target="_blank">
            <button class="btn btn-white social icon-linkedin"></button>
        </a>
    </div>
    <div class="slider slider-social">
        <div class="social-slide">
            <a href="#" class="image-wrapper">
                <img src="/images/social/1.jpg">
            </a>
        </div>
        <div class="social-slide">
            <div class="text-wrapper">
                <p>
                    Četvrti PHP Conference krajem maja u Beogradu – zajedno sa osnivačem PHP-a!
                    <a href="#">http://buff.ly/2m7Tx6B</a> cc <a href="#">@PHPSrbija</a>
                </p>
            </div>
        </div>
        <div class="social-slide">
            <a href="#" class="image-wrapper">
                <img src="/images/social/2.jpg">
            </a>
        </div>
        <div class="social-slide">
            <div class="text-wrapper">
                <p>
                    We are so proud to have Pirate Technologies as our Gold sponsor for the second year in a row!
                    <a href="#">http://conf2017.phpsrbija.rs/</a> <a href="#">#phpsrb17</a>
                </p>
            </div>
        </div>
        <div class="social-slide">
            <div class="text-wrapper">
                <p>Presenting our Gold sponsor - Quantox Technology <a
                            href="#">http://www.conf2017.phpsrbija.rs/post/9</a> <a href="#">#phpsrb17</a></p>
            </div>
        </div>
        <div class="social-slide">
            <a href="#" class="image-wrapper">
                <img src="/images/social/1.jpg">
            </a>
        </div>
        <div class="social-slide">
            <div class="text-wrapper">
                <p>Presenting our Gold sponsor - Quantox Technology <a
                            href="#">http://www.conf2017.phpsrbija.rs/post/9</a> <a href="#">#phpsrb17</a></p>
            </div>
        </div>
        <div class="social-slide">
            <a href="#" class="image-wrapper">
                <img src="/images/social/1.jpg">
            </a>
        </div>
    </div>
</div>

<div class="society">
    <div class="intro">
        <div class="meet">Upoznajte članove udruženja</div>
        <a class="link reload icon-reload" href="#"></a>
    </div>
    <div class="members">
        <article>
            <img src="/images/members/1.jpg">
            <div class="hover-box">
                <div class="center-box">
                    <div class="inner-box y-centered">
                        <p class="name">Nemanja Čedomirović</p>
                        <p class="title">Jedan od osnivača Udruženja PHP Srbija.</p>
                    </div>
                </div>
                <button class="btn btn-link icon-close"></button>
            </div>

        </article>
        <article>
            <img src="/images/members/2.jpg">
            <div class="hover-box">
                <div class="center-box">
                    <div class="inner-box y-centered">
                        <p class="name">Nemanja Čedomirović</p>
                        <p class="title">Jedan od osnivača Udruženja PHP Srbija.</p>
                    </div>
                </div>
                <button class="btn btn-link icon-close"></button>
            </div>

        </article>
        <article>
            <img src="/images/members/3.jpg">
            <div class="hover-box">
                <div class="center-box">
                    <div class="inner-box y-centered">
                        <p class="name">Nemanja Čedomirović</p>
                        <p class="title">Jedan od osnivača Udruženja PHP Srbija.</p>
                    </div>
                </div>
                <button class="btn btn-link icon-close"></button>
            </div>

        </article>
        <article>
            <img src="/images/members/4.jpg">
            <div class="hover-box">
                <div class="center-box">
                    <div class="inner-box y-centered">
                        <p class="name">Nemanja Čedomirović</p>
                        <p class="title">Jedan od osnivača Udruženja PHP Srbija.</p>
                    </div>
                </div>
                <button class="btn btn-link icon-close"></button>
            </div>

        </article>
        <article>
            <img src="/images/members/5.jpg">
            <div class="hover-box">
                <div class="center-box">
                    <div class="inner-box y-centered">
                        <p class="name">Nemanja Čedomirović</p>
                        <p class="title">Jedan od osnivača Udruženja PHP Srbija.</p>
                    </div>
                </div>
                <button class="btn btn-link icon-close"></button>
            </div>

        </article>
        <article class="add">
            <a class="link abs-wrapper" href="#">
                <div class="center">
                    <div class="add-user"></div>
                    <div class="you">PRIKLJUČI SE I TI</div>
                </div>
            </a>
        </article>
    </div>
</div>

<?php // $article->body; ?>