<div id="sub-content">
    <div class="jumbotron">
        <h1>Unfinished</h1>
        <p class="lead">[TLDR] Fast, enterprise CMS given to the community</p>
        <br/>
        <p class="lead" style="text-align: justify;">
            <small>
                Unfinished is a Open Source project. Dedicated to the needs of user group "PHPSerbia" but it can be
                widely used. It is developed by programers heavly oriented to <strike>the best</strike> new pratice in
                PHP community. Technology stack for the project is: PHP7, MySQL. Middlewares is used for onion
                architecture and conrollers/actions and DDD for core layers. The project is currently in progress...
            </small>
        </p>
        <br/>
        <p>
            <a class="btn btn-lg btn-success" href="<?= $this->url('auth', ['action' => 'login']) ?>" role="button">
                Admin Login
            </a>
        </p>
        <small>Pssst, user is: <b>admin@unfinished.com</b> and pass: <b>testtest</b></small>
    </div>

    <div class="row marketing">
        <div class="col-lg-6">
            <h4>Subheading</h4>
            <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

            <h4>Subheading</h4>
            <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet
                fermentum.</p>

            <h4>Subheading</h4>
            <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
        </div>

        <div class="col-lg-6">
            <h4>Subheading</h4>
            <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

            <h4>Subheading</h4>
            <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet
                fermentum.</p>

            <h4>Subheading</h4>
            <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
        </div>
    </div>
</div>
