<div class="blog-page-single">
    <div class="headline">
        <div class="image" style="background-image: url('<?= $post->featured_img ?>')"></div>
        <div class="headline-text">
            <div class="title"><?= $post->title ?></div>
            <div class="author">Autor:
                <strong><?= $post->first_name . ' ' . $post->last_name; ?></strong> |
            </div>
            <div class="date">Datum:
                <time><?= date('d.m.Y H:i', strtotime($post->published_at)) ?></time>
            </div>
            <ul class="tags-wrapper">
                <li># <?= $post->category_name ?></li>
            </ul>
        </div>
    </div>
    <div class="blog-single-wrapper">
        <div class="social-share">
            <div class="social-icons social-icon__vertical">
                <div class="social-icon-shared">
                    <strong>142</strong>
                    <span>Podeljeno</span>
                </div>
                <a href="#" target="_blank">
                    <button class="btn btn-white social icon-facebook"></button>
                </a>
                <a href="#" target="_blank">
                    <button class="btn btn-white social icon-twitter"></button>
                </a>
                <a href="#" target="_blank">
                    <button class="btn btn-white social icon-linkedin"></button>
                </a>
            </div>
        </div>
        <div class="blog-text">
            <?= $post->body ?>
            <!--
            <div class="show-more">
                <a class="btn btn-white btn-block" data-history data-ajax="/blog-1.html" href="/comments/1">Prikaži 25
                    komentara</a>
            </div>
            -->
        </div>
    </div>
</div>
<div class="half-pagination">
    <div class="paginate-prev">
        <?php if($previous): ?>
            <a href="<?= $this->url('post', ['segment_1' => $previous->category_slug, 'segment_2' => $previous->slug]) ?>">
                <small>Prethodni članak</small>
                <div class="title"><?= $previous->title ?></div>
            </a>
        <?php endif; ?>
    </div>
    <div class="paginate-next">
        <?php if($next): ?>
            <a href="<?= $this->url('post', ['segment_1' => $next->category_slug, 'segment_2' => $next->slug]) ?>">
                <small>Sledeći članak</small>
                <div class="title"><?= $next->title ?></div>
            </a>
        <?php endif; ?>
    </div>
</div>