<div class="blog-page-single">
    <div class="headline">
        <div class="image"
             style="background-image: url('http://beta.phpsrbija.rs/uploads/b/d/9/bd9d1f62d90cd6e7b7783cf4945fb723.jpg')"></div>
        <div class="headline-text">
            <div class="title">„Fake it until you make it“</div>
            <div class="author">Autor:
                <strong>PHP Serbia</strong> |
            </div>
            <div class="date">Datum:
                <time>23.05.2017 12:00</time>
            </div>
            <ul class="tags-wrapper">
                <li># Undefined</li>
            </ul>
        </div>
    </div>
    <div class="blog-single-wrapper">
        <div class="social-share">
            <div class="social-icons social-icon__vertical">
                <div class="social-icon-shared">
                    <strong>5789</strong>
                    <span>Podeljeno</span>
                </div>
                <a href="#" target="_blank">
                    <button class="btn btn-white social icon-facebook"></button>
                </a>
                <a href="#" target="_blank">
                    <button class="btn btn-white social icon-twitter"></button>
                </a>
                <a href="#" target="_blank">
                    <button class="btn btn-white social icon-linkedin"></button>
                </a>
            </div>
        </div>
        <div class="blog-text">
            <p style="text-align: justify;">
                Teks koji opisuje sta planiramo ad uradimo i da na tome radimo i da ce uskoro biti :) <br/><br/>

                U svetu informacionih tehnologija i računarskih nauka dominiraju mu&scaron;karci
                kako brojčano tako i &scaron;to se tiče pozicija na kojima su. To je činjenica koja nije upitna. Ono oko
                čega se moze sporiti&nbsp;jeste da li je uop&scaron;te vredno diskutovati&nbsp;takvo stanje stvari, koji
                su razlozi za takav odnos polova kao i ima li prostora da se tu ne&scaron;to promeni.<br/><br/>
            </p>

            <h2 style="text-align: center;">
                Ovo je stranice za koju treba napisati PR teks koji objasnjava sta je to "soon"
            </h2>
            <br/><br/>


            <p style="text-align: justify;">

                U svetu informacionih tehnologija i računarskih nauka dominiraju mu&scaron;karci
                kako brojčano tako i &scaron;to se tiče pozicija na kojima su. To je činjenica koja nije upitna. Ono oko
                čega se moze sporiti&nbsp;jeste da li je uop&scaron;te vredno diskutovati&nbsp;takvo stanje stvari, koji
                su razlozi za takav odnos polova kao i ima li prostora da se tu ne&scaron;to promeni.<br/><br/>

                Srecno kodiranje!
            </p>

        </div>
    </div>
</div>