<?php
$video   = $videos->getTotalItemCount() ? $videos->getItem(0) : null;
$escaper = (new \Zend\Escaper\Escaper);
$this->headTitle($escaper->escapeHtml($category->title));
$this->headMeta($escaper->escapeHtml($category->description), 'description');
$this->headMeta('videos', 'og:type');
$this->headMeta($category->main_img ? $this->serverUrl($category->main_img) : '', 'og:image');
$this->headMeta($this->serverUrl(), 'og:url');
$this->headMeta($escaper->escapeHtml($category->description), 'og:description');
?>
<div class="video-page">
    <div class="headline">
        <div class="image" style="background-image: url('<?= $video ? $video->featured_img : '' ?>')"></div>

        <div class="headline-text">
            <div class="category">Video</div>
            <div class="title">
                <a href="<?= $this->url('video', ['video_slug' => $video->slug]) ?>" class="title">
                    <?= $video ? $video->title : '' ?>
                </a>
            </div>
            <div class="instructor">Predavač: <?= $video ? $video->sub_title : '' ?></div>
        </div>
    </div>
    <ul class="video-tags-wrapper">
        <!--
       <li><a class="link tag" href="#">Sve</a></li>
       <li><a class="link tag" href="#">Konferencija</a></li>
       <li><a class="link tag" href="#">Meetup</a></li>
       <li><a class="link tag" href="#">Video vesti</a></li>
        -->
    </ul>

    <div class="video-wrapper">
        <div class="video-posts">
            <div class="clearfix">

                <?php foreach($videos as $video): ?>
                    <a href="<?= $this->url('video', ['video_slug' => $video->slug]) ?>" class="video-post">
                        <div class="image-wrapper-none">
                            <img src="<?= $video->main_img ?>">

                            <div class="video-box-hover"><img src="/images/videos/play.png" alt="Play"></div>
                        </div>
                        <div class="video-box-content">
                            <div class="category">Video</div>
                            <div class="title"><?= $video->title ?></div>
                            <div class="instructor">Predavač: <?= $video->sub_title ?></div>
                        </div>
                    </a>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>

<div class="half-pagination">
    <?= $this->paginationControl($videos, 'Sliding', 'article/pagination', ['route' => 'category']) ?>
</div>