<?php $this->headTitle($this->status . ' ' . $this->reason); ?>

<h1>Oops!</h1>
<h2>This is awkward.</h2>
<p>We encountered a <?php echo $this->escapeHtml(sprintf('%d %s', $this->status, $this->reason)); ?> error.</p><hr/>

<?php if(isset($this->error)): ?>
    <hr/>
    <h2>Additional information: </h2>
    <h3><?php echo get_class($this->error); ?></h3>
    <dl>
        <dt>File:</dt>
        <dd><pre class="prettyprint linenums"><?php echo $this->error->getFile() ?>:<?php echo $this->error->getLine() ?></pre></dd>
        <dt>Message:</dt>
        <dd><pre class="prettyprint linenums"><?php echo $this->escapeHtml($this->error->getMessage()) ?></pre></dd>
        <dt>Stack trace:</dt>
        <dd><pre class="prettyprint linenums"><?php echo $this->escapeHtml($this->error->getTraceAsString()) ?></pre></dd>
    </dl>
    <?php
    $e      = $this->error->getPrevious();
    $icount = 0;
    ?>

    <?php if($e) : ?>
        <hr/>
        <h2>Previous exceptions:</h2>
        <ul class="unstyled">
            <?php while($e) : ?>
                <li>
                    <h3><?php echo get_class($e); ?></h3>
                    <dl>
                        <dt>File:</dt>
                        <dd><pre class="prettyprint linenums"><?php echo $e->getFile() ?> :<?php echo $e->getLine() ?></pre></dd>
                        <dt>Message:</dt>
                        <dd><pre class="prettyprint linenums"><?php echo $this->escapeHtml($e->getMessage()) ?></pre></dd>
                        <dt>Stack trace:</dt>
                        <dd><pre class="prettyprint linenums"><?php echo $this->escapeHtml($e->getTraceAsString()) ?></pre></dd>
                    </dl>
                </li>
                <?php
                $e = $e->getPrevious();
                $icount += 1;
                if($icount >= 50){
                    echo "<li>There may be more exceptions, but we show only 50.</li>";
                    break;
                }
                ?>
            <?php endwhile; ?>
        </ul>
    <?php endif; ?>
<?php else: ?>
    <h3>No Exception available</h3>
<?php endif ?>