<!-- Flat style parent and children items -->
<ul>
    <?php foreach($this->menu()->getFooterMenu() as $item): ?>
        <?php if($item['children']): ?>
            <?php foreach($item['children'] as $child): ?>
                <?php $href = $this->menuUrl($child) ?>
                <li>
                    <a href="<?= $href ?>" <?= (strpos($href, 'http') === 0) ? 'target="_blank"' : '' ?>>
                        <?= $child['title'] ?>
                    </a>
                </li>
            <?php endforeach; ?>
        <?php else: ?>
            <?php $href = $this->menuUrl($item) ?>
            <li>
                <a href="<?= $href ?>" <?= (strpos($href, 'http') === 0) ? 'target="_blank"' : '' ?>>
                    <?= $item['title'] ?>
                </a>
            </li>
        <?php endif; ?>
    <?php endforeach; ?>
</ul>