<?php if($this->pageCount > 1): ?>
    <div class="paginate-prev">
        <?php if(isset($this->previous)): ?>
            <a href="<?php echo $this->url($this->route, isset($this->data) ? $this->data : []); ?>?page=<?php echo $this->previous; ?>">
                <small></small>
                <div class="title">&#8637; Prethodna stranica</div>
            </a>
        <?php else: ?>
            <a href="#">
                <small></small>
                <div class="title">Prva :)</div>
            </a>
        <?php endif; ?>
    </div>
    <div class="paginate-next">
        <?php if(isset($this->next)): ?>
            <a href="<?php echo $this->url($this->route, isset($this->data) ? $this->data : []); ?>?page=<?php echo $this->next; ?>">
                <small></small>
                <div class="title">Sledeća stranica &#8640;</div>
            </a>
        <?php else: ?>
            <a href="#">
                <small></small>
                <div class="title">Poslednja :D</div>
            </a>
        <?php endif; ?>
    </div>
<?php endif; ?>

