<div class="">
    <div class="page-title">
        <div class="title_left">
            <h3>categorys
                <small> / List of all categories.</small>
            </h3>
        </div>
        <div class="title_right">
            <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
                      <button class="btn btn-default" type="button">Go!</button>
                    </span>
                </div>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <a href="<?= $this->url('admin.categories.action', ['action' => 'edit', 'id' => 0]) ?>"
                       class="btn btn-default pull-right btn-success"> Create new category
                    </a>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <?php if($list->getTotalItemCount() > 0): ?>
                        <table class="table">
                            <thead>
                            <tr>
                                <th>Name</th>
                                <th>Slug</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach($list as $one): ?>
                                <tr>
                                    <td><?= $one->name ?></td>
                                    <td><?= $one->slug ?></td>
                                    <td>
                                        <span class="pull-right">
                                            <a href="<?= $this->url('admin.categories.action', ['action' => 'edit', 'id' => $one->category_id]) ?>">
                                                <i class="glyphicon glyphicon-pencil"></i>
                                            </a>
                                        </span>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                            </tbody>
                        </table>
                        <?= $this->paginationControl($list, 'Sliding', 'admin/pagination', ['route' => 'admin.categories']) ?>
                    <?php else: ?>
                        <div class="col-md-offset-3 col-sm-offset-3 col-md-6 col-sm-6 col-xs-12">
                            <div class="jumbotron text-center">
                                <h3>There are no categories!</h3>
                            </div>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
</div>