<div class="row">
    <div class="col-md-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>
                    <?php if(isset($event->article_id) && $event->article_id): ?>
                        <h2>Edit Post: "<?= $event->title ?>"</h2>
                    <?php else: ?>
                        <h2>Write new Post</h2>
                    <?php endif; ?>
                </h2>
                <a href="<?= $this->url('admin.events') ?>" class="btn btn-default pull-right">
                    <i class="fa fa-reply"></i> Back
                </a>
                <div class="clearfix"></div>
            </div>
            <div class="x_content"><br/>
                <form class="form-horizontal form-label-left" method="POST" enctype="multipart/form-data"
                      action="<?= $this->url('admin.events.action', ['action' => 'save', 'id' => $event ? $event->article_id : 0]) ?>">
                    <div class="row">
                        <div class="col-md-8 col-xs-12">
                            <!-- Content part -->
                            <div class="form-group">
                                <div class="col-md-12 col-sm-12 col-xs-12">
                                    <textarea class="form-control" id="body" name="body"
                                              placeholder="Write content..."><?= $event ? $event->body : '' ?></textarea>
                                    <ul class="parsley-errors-list">
                                        <li class="">
                                            <?= (isset($errors->body) ? implode('. ', (array)$errors->body) : ''); ?>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <!-- \Content part -->
                        </div>
                        <div class="col-md-4 col-xs-12">
                            <!-- Rest configuration for Event -->
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">Title</label>
                                <div class="col-md-9 col-sm-9 col-xs-12">
                                    <input type="text" class="form-control" name="title" placeholder="Title"
                                           value="<?= $event ? $event->title : '' ?>">
                                    <ul class="parsley-errors-list">
                                        <li class="">
                                            <?= (isset($errors->title) ? implode('. ', (array)$errors->title) : ''); ?>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">Sub title</label>
                                <div class="col-md-9 col-sm-9 col-xs-12">
                                    <input type="text" class="form-control" name="sub_title" placeholder="Sub title"
                                           value="<?= $event ? $event->sub_title : '' ?>">
                                    <ul class="parsley-errors-list">
                                        <li class="">
                                            <?= (isset($errors->title) ? implode('. ', (array)$errors->title) : ''); ?>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">Published Date</label>
                                <div class="col-md-9 col-sm-9 col-xs-12  has-feedback">
                                    <input type="text" class="form-control has-feedback-left" id="published_at_calendar"
                                           name="published_at" value="<?= $event ? $event->published_at : '' ?>"
                                           placeholder="Published Date" aria-describedby="inputSuccess2Status2">
                                    <span class="fa fa-calendar-o form-control-feedback left" aria-hidden="true"></span>

                                    <ul class="parsley-errors-list">
                                        <li class="">
                                            <?= (isset($errors->published_at) ? implode('. ', (array)$errors->published_at) : ''); ?>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">URL Slug</label>
                                <div class="col-md-9 col-sm-9 col-xs-12">
                                    <input type="text" class="form-control" name="slug" placeholder="URL Slug"
                                           value="<?= $event ? $event->slug : '' ?>">
                                    <ul class="parsley-errors-list">
                                        <li class="">
                                            <?= (isset($errors->slug) ? implode('. ', (array)$errors->slug) : ''); ?>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">Place</label>
                                <div class="col-md-9 col-sm-9 col-xs-12">
                                    <input type="text" class="form-control" name="place_name" placeholder="Place name"
                                           value="<?= $event ? $event->place_name : '' ?>">
                                    <ul class="parsley-errors-list">
                                        <li class="">
                                            <?= (isset($errors->place_name) ? implode('. ', (array)$errors->place_name) : ''); ?>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">Longitude</label>
                                <div class="col-md-9 col-sm-9 col-xs-12">
                                    <input type="text" class="form-control" name="longitude" placeholder="longitude"
                                           value="<?= $event ? $event->longitude : '' ?>">
                                    <ul class="parsley-errors-list">
                                        <li class="">
                                            <?= (isset($errors->longitude) ? implode('. ', (array)$errors->longitude) : ''); ?>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">Latitude</label>
                                <div class="col-md-9 col-sm-9 col-xs-12">
                                    <input type="text" class="form-control" name="latitude" placeholder="latitude"
                                           value="<?= $event ? $event->latitude : '' ?>">
                                    <ul class="parsley-errors-list">
                                        <li class="">
                                            <?= (isset($errors->latitude) ? implode('. ', (array)$errors->latitude) : ''); ?>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">Start at</label>
                                <div class="col-md-9 col-sm-9 col-xs-12  has-feedback">
                                    <input type="text" class="form-control has-feedback-left" id="start_at_calendar"
                                           name="start_at" value="<?= $event ? $event->start_at : '' ?>"
                                           placeholder="Start at" aria-describedby="inputSuccess2Status2">
                                    <span class="fa fa-calendar-o form-control-feedback left" aria-hidden="true"></span>
                                    <ul class="parsley-errors-list">
                                        <li class="">
                                            <?= (isset($errors->start_at) ? implode('. ', (array)$errors->start_at) : ''); ?>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">End at</label>
                                <div class="col-md-9 col-sm-9 col-xs-12  has-feedback">
                                    <input type="text" class="form-control has-feedback-left" id="end_at_calendar"
                                           name="end_at" value="<?= $event ? $event->end_at : '' ?>"
                                           placeholder="End at" aria-describedby="inputSuccess2Status2">
                                    <span class="fa fa-calendar-o form-control-feedback left" aria-hidden="true"></span>
                                    <ul class="parsley-errors-list">
                                        <li class="">
                                            <?= (isset($errors->end_at) ? implode('. ', (array)$errors->end_at) : ''); ?>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">Featured image</label>
                                <div class="col-md-9 col-sm-9 col-xs-12">
                                    <input type="file" class="form-control" name="featured_img"
                                           placeholder="Featured image"
                                           value="<?= isset($event->featured_img) ? $event->featured_img : '' ?>">
                                    <ul class="parsley-errors-list">
                                        <li class="">
                                            <?= (isset($errors->featured_img) ? implode('. ', (array)$errors->featured_img) : ''); ?>
                                        </li>
                                    </ul>
                                    <?php if(isset($event->featured_img) && $event->featured_img): ?>
                                        <img src="<?= $event->featured_img ?>" style="max-height: 100px;"/>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">Main image</label>
                                <div class="col-md-9 col-sm-9 col-xs-12">
                                    <input type="file" class="form-control" name="main_img" placeholder="Main image"
                                           value="<?= isset($event->main_img) ? $event->main_img : '' ?>">
                                    <ul class="parsley-errors-list">
                                        <li class="">
                                            <?= (isset($errors->main_img) ? implode('. ', (array)$errors->main_img) : ''); ?>
                                        </li>
                                    </ul>
                                    <?php if(isset($event->main_img) && $event->main_img): ?>
                                        <img src="<?= $event->main_img ?>" style="max-height: 100px;"/>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">Tags</label>
                                <div class="col-md-9 col-sm-9 col-xs-12">
                                    <select class="select2_multiple form-control" multiple="multiple" name="tags[]">
                                        <?php foreach($tags as $tag): ?>
                                            <option value="<?= $tag->tag_id ?>" <?= (isset($event->tags) && in_array($tag->tag_id, $event->tags)) ? 'selected' : '' ?>>
                                                <?= $tag->name ?>
                                            </option>
                                        <?php endforeach; ?>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">Published</label>
                                <div class="col-md-9 col-sm-9 col-xs-12">
                                    <input type="checkbox" class="js-switch" value="1"
                                           name="status" <?= (isset($event->status) && $event->status == 1) ? 'checked' : ''; ?> />
                                    <ul class="parsley-errors-list">
                                        <li class="">
                                            <?= (isset($errors->status) ? implode('. ', (array)$errors->status) : ''); ?>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-offset-3 col-sm-offset-3 col-md-9 col-sm-9 col-xs-12">
                                    <button type="submit" class="btn btn-block btn-success">Save</button>
                                    <br/>
                                    <a type="button" class="btn btn-default btn-block"
                                       href="<?= $this->url('admin.events') ?>">
                                        Cancel
                                    </a>
                                    <?php if(isset($event->article_id) && $event->article_id): ?>
                                        <br/>
                                        <a href="<?= $this->url('admin.events.action', ['action' => 'delete', 'id' => $event->article_id]) ?>"
                                           onclick="if(!confirm('Are you sure?')){return false;}"
                                           class="btn btn-danger btn-block"> Delete
                                        </a>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <!-- \Rest configuration for Event -->
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<?php
$this->inlineScript()->appendScript("
    $(document).ready(function() {
        initMce('#body', '100%', 650, true);

        $('.articleForm').on('submit', function(e) {
            tinyMCE.triggerSave();
        });
        
        $('#published_at_calendar').daterangepicker({
            timePicker24Hour: true,
            timePicker: true,
            locale: {
                format: 'YYYY-MM-DD HH:mm:ss'
            },
            singleDatePicker: true
		}, function(start, end, label) {
	        // console.log(start.toISOString(), end.toISOString(), label);
		});
		
		$('#start_at_calendar').daterangepicker({
            timePicker24Hour: true,
            timePicker: true,
            locale: {
                format: 'YYYY-MM-DD HH:mm:ss'
            },
            singleDatePicker: true
		}, function(start, end, label) {
	        // console.log(start.toISOString(), end.toISOString(), label);
		});
		
		$('#end_at_calendar').daterangepicker({
            timePicker24Hour: true,
            timePicker: true,
            locale: {
                format: 'YYYY-MM-DD HH:mm:ss'
            },
            singleDatePicker: true
		}, function(start, end, label) {
	        // console.log(start.toISOString(), end.toISOString(), label);
		});
    });
");
?>