<div class="row">
    <div class="col-md-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>
                    <?php if(isset($user->admin_user_id) && $user->admin_user_id): ?>
                        <h2>Edit admin user: "<?= $user->first_name . ' ' . $user->last_name ?>"</h2>
                    <?php else: ?>
                        <h2>Add new user</h2>
                    <?php endif; ?>
                </h2>
                <a href="<?= $this->url('admin.users') ?>" class="btn btn-default pull-right">
                    <i class="fa fa-reply"></i> Back</a>
                <div class="clearfix"></div>
            </div>
            <div class="x_content"><br/>
                <form class="form-horizontal form-label-left" method="POST" enctype="multipart/form-data"
                      action="<?= $this->url('admin.users.action', ['action' => 'save', 'id' => $user ? $user->admin_user_id : 0]) ?>">
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">First Name</label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="text" class="form-control" name="first_name" placeholder="First Name"
                                   value="<?= $user ? $user->first_name : '' ?>">
                            <ul class="parsley-errors-list">
                                <li class="">
                                    <?= (isset($errors->first_name) ? implode('. ', (array)$errors->first_name) : ''); ?>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Last Name</label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="text" class="form-control" name="last_name" placeholder="Last Name"
                                   value="<?= $user ? $user->last_name : '' ?>">
                            <ul class="parsley-errors-list">
                                <li class="">
                                    <?= (isset($errors->last_name) ? implode('. ', (array)$errors->last_name) : ''); ?>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Email</label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="text" class="form-control" name="email" placeholder="Email"
                                   value="<?= $user ? $user->email : '' ?>">
                            <ul class="parsley-errors-list">
                                <li class="">
                                    <?= (isset($errors->email) ? implode('. ', (array)$errors->email) : ''); ?>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Introduction</label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="text" class="form-control" name="introduction" placeholder="Introduction"
                                   value="<?= $user ? $user->introduction : '' ?>">
                            <ul class="parsley-errors-list">
                                <li class="">
                                    <?= (isset($errors->introduction) ? implode('. ', (array)$errors->introduction) : ''); ?>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Active</label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <select class="form-control" name="status">
                                <option value="1" <?= ($user && $user->status == 1) ? 'selected' : '' ?>>
                                    Activated
                                </option>
                                <option value="0" <?= ($user && $user->status == 0) ? 'selected' : '' ?>>
                                    Deactivated
                                </option>
                            </select>
                            <ul class="parsley-errors-list">
                                <li class="">
                                    <?= (isset($errors->status) ? implode('. ', (array)$errors->status) : ''); ?>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Face image</label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="file" class="form-control" name="face_img"
                                   placeholder="Face image"
                                   value="<?= isset($user->face_img) ? $user->face_img : '' ?>">
                            <ul class="parsley-errors-list">
                                <li class="">
                                    <?= (isset($errors->face_img) ? implode('. ', (array)$errors->face_img) : ''); ?>
                                </li>
                            </ul>
                            <?php if(isset($user->face_img) && $user->face_img): ?>
                                <img src="<?= $user->face_img ?>" style="max-height: 100px;"/>
                            <?php endif; ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Profile image</label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="file" class="form-control" name="profile_img" placeholder="Profile image"
                                   value="<?= isset($user->profile_img) ? $user->profile_img : '' ?>">
                            <ul class="parsley-errors-list">
                                <li class="">
                                    <?= (isset($errors->profile_img) ? implode('. ', (array)$errors->profile_img) : ''); ?>
                                </li>
                            </ul>
                            <?php if(isset($user->profile_img) && $user->profile_img): ?>
                                <img src="<?= $user->profile_img ?>" style="max-height: 100px;"/>
                            <?php endif; ?>
                        </div>
                    </div>


                    <div class="divider-dashed"></div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Password</label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="password" class="form-control" name="password" placeholder="Password"/>
                            <ul class="parsley-errors-list">
                                <li class="">
                                    <?= (isset($errors->password) ? implode('. ', (array)$errors->password) : ''); ?>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Confirm Password</label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="password" class="form-control" name="confirm_password"
                                   placeholder="Confirm Password"/>
                            <ul class="parsley-errors-list">
                                <li class="">
                                    <?= (isset($errors->confirm_password) ? implode('. ', (array)$errors->confirm_password) : ''); ?>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                            <button type="submit" class="btn btn-success">Save</button>
                            <a type="button" class="btn btn-default" href="<?= $this->url('admin.users') ?>">
                                Cancel
                            </a>
                            <?php if(isset($user->admin_user_id) && $user->admin_user_id): ?>
                                <a href="<?= $this->url('admin.users.action', ['action' => 'delete', 'id' => $user->admin_user_id]) ?>"
                                   onclick="if(!confirm('Are you sure?')){return false;}"
                                   class="btn btn-danger pull-right"> Delete
                                </a>
                            <?php endif; ?>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>