<div class="row">
    <div class="col-md-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>
                    <?php if(isset($video->article_id) && $video->article_id): ?>
                        <h2>Video: "<?= $video->title ?>"</h2>
                    <?php else: ?>
                        <h2>Publish new Video</h2>
                    <?php endif; ?>
                </h2>
                <a href="<?= $this->url('admin.videos') ?>" class="btn btn-default pull-right">
                    <i class="fa fa-reply"></i> Back
                </a>
                <div class="clearfix"></div>
            </div>
            <div class="x_content"><br/>
                <form class="form-horizontal form-label-left" method="POST" enctype="multipart/form-data"
                      action="<?= $this->url('admin.videos.action', ['action' => 'save', 'id' => $video ? $video->article_id : 0]) ?>">
                    <div class="row">
                        <div class="col-md-8 col-xs-12">
                            <!-- Content part -->
                            <div class="form-group">

                                <div class="col-md-12 col-sm-12 col-xs-12">
                                    <textarea class="form-control" id="body" name="body"
                                              placeholder="Write content..."><?= $video ? $video->body : '' ?></textarea>
                                    <ul class="parsley-errors-list">
                                        <li class="">
                                            <?= (isset($errors->body) ? implode('. ', (array)$errors->body) : ''); ?>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <!-- \Content part -->
                        </div>
                        <div class="col-md-4 col-xs-12">
                            <!-- Rest configuration for Post -->
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">Title</label>
                                <div class="col-md-9 col-sm-9 col-xs-12">
                                    <input type="text" class="form-control" name="title" placeholder="Title"
                                           value="<?= $video ? $video->title : '' ?>">
                                    <ul class="parsley-errors-list">
                                        <li class="">
                                            <?= (isset($errors->title) ? implode('. ', (array)$errors->title) : ''); ?>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">Published Date</label>
                                <div class="col-md-9 col-sm-9 col-xs-12  has-feedback">
                                    <input type="text" class="form-control has-feedback-left" id="published_at_calendar"
                                           name="published_at" value="<?= $video ? $video->published_at : '' ?>"
                                           placeholder="Published Date" aria-describedby="inputSuccess2Status2">
                                    <span class="fa fa-calendar-o form-control-feedback left" aria-hidden="true"></span>

                                    <ul class="parsley-errors-list">
                                        <li class="">
                                            <?= (isset($errors->published_at) ? implode('. ', (array)$errors->published_at) : ''); ?>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">Intro</label>
                                <div class="col-md-9 col-sm-9 col-xs-12">
                                    <textarea class="form-control" rows="3" name="lead"
                                              placeholder="Intro..."><?= $video ? $video->lead : '' ?></textarea>
                                    <ul class="parsley-errors-list">
                                        <li class="">
                                            <?= (isset($errors->lead) ? implode('. ', (array)$errors->lead) : ''); ?>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">Embed code</label>
                                <div class="col-md-9 col-sm-9 col-xs-12">
                                    <div class="videoPreview"></div>
                                    <textarea class="form-control" rows="3" name="embed_code"
                                              placeholder="Embed code..."><?= $video ? $video->embed_code : '' ?></textarea>
                                    <ul class="parsley-errors-list">
                                        <li class="">
                                            <?= (isset($errors->embed_code) ? implode('. ', (array)$errors->embed_code) : ''); ?>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">URL Slug</label>
                                <div class="col-md-9 col-sm-9 col-xs-12">
                                    <input type="text" class="form-control" name="slug" placeholder="URL Slug"
                                           value="<?= $video ? $video->slug : '' ?>">
                                    <ul class="parsley-errors-list">
                                        <li class="">
                                            <?= (isset($errors->slug) ? implode('. ', (array)$errors->slug) : ''); ?>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">Featured image</label>
                                <div class="col-md-9 col-sm-9 col-xs-12">
                                    <input type="file" class="form-control" name="featured_img"
                                           placeholder="Featured image"
                                           value="<?= isset($video->featured_img) ? $video->featured_img : '' ?>">
                                    <ul class="parsley-errors-list">
                                        <li class="">
                                            <?= (isset($errors->featured_img) ? implode('. ', (array)$errors->featured_img) : ''); ?>
                                        </li>
                                    </ul>
                                    <?php if(isset($video->featured_img) && $video->featured_img): ?>
                                        <img src="<?= $video->featured_img ?>" style="max-height: 100px;"/>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">Main image</label>
                                <div class="col-md-9 col-sm-9 col-xs-12">
                                    <input type="file" class="form-control" name="main_img" placeholder="Main image"
                                           value="<?= isset($video->main_img) ? $video->main_img : '' ?>">
                                    <ul class="parsley-errors-list">
                                        <li class="">
                                            <?= (isset($errors->main_img) ? implode('. ', (array)$errors->main_img) : ''); ?>
                                        </li>
                                    </ul>
                                    <?php if(isset($video->main_img) && $video->main_img): ?>
                                        <img src="<?= $video->main_img ?>" style="max-height: 100px;"/>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">Tags</label>
                                <div class="col-md-9 col-sm-9 col-xs-12">
                                    <select class="select2_multiple form-control" multiple="multiple" name="tags[]">
                                        <?php foreach($tags as $tag): ?>
                                            <option value="<?= $tag->tag_id ?>" <?= (isset($video->tags) && in_array($tag->tag_id, $video->tags)) ? 'selected' : '' ?>>
                                                <?= $tag->name ?>
                                            </option>
                                        <?php endforeach; ?>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">Published</label>
                                <div class="col-md-9 col-sm-9 col-xs-12">
                                    <input type="checkbox" class="js-switch" value="1"
                                           name="status" <?= (isset($video->status) && $video->status == 1) ? 'checked' : ''; ?> />
                                    <ul class="parsley-errors-list">
                                        <li class="">
                                            <?= (isset($errors->status) ? implode('. ', (array)$errors->status) : ''); ?>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-offset-3 col-sm-offset-3 col-md-9 col-sm-9 col-xs-12">
                                    <button type="submit" class="btn btn-block btn-success">Save</button>
                                    <br/>
                                    <a type="button" class="btn btn-default btn-block"
                                       href="<?= $this->url('admin.videos') ?>">
                                        Cancel
                                    </a>
                                    <?php if(isset($video->article_id) && $video->article_id): ?>
                                        <br/>
                                        <a href="<?= $this->url('admin.videos.action', ['action' => 'delete', 'id' => $video->article_id]) ?>"
                                           onclick="if(!confirm('Are you sure?')){return false;}"
                                           class="btn btn-danger btn-block"> Delete
                                        </a>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <!-- \Rest configuration for Post -->
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<?php
$this->inlineScript()->appendScript("
    $(document).ready(function() {
        initMce('#body', '100%', 500, true);

        $('.articleForm').on('submit', function(e) {
            tinyMCE.triggerSave();
        });
        
        $('#published_at_calendar').daterangepicker({
            timePicker24Hour: true,
            timePicker: true,
            locale: {
                format: 'YYYY-MM-DD HH:mm:ss'
            },
            singleDatePicker: true
		}, function(start, end, label) {
	        // console.log(start.toISOString(), end.toISOString(), label);
		});
		
		// Video preview
        var oldVal = '';
        $('.embedCode').on('change textInput input', function(e) {
            if($(this).hasClass('embedCode') && $(this).html().length){
                setTimeout(function () {
                    console.log($($('.embedCode').text()).attr('src'));
                }, 100);
            var iframe = \"<iframe width='560' height='315' frameborder='0' allowfullscreen></iframe>\";
            $('.videoPreview').html(iframe);
            console.log($($('.embedCode').text()).attr('src'));
            $('.videoPreview iframe').attr('src', $($('.embedCode').text()).attr('src'));
            }
        });
        // \Video preview
		
    });
");
?>
