<?php
$escaper = (new \Zend\Escaper\Escaper);
$this->headTitle($escaper->escapeHtml($video->title));
$this->headMeta($escaper->escapeHtml($video->lead), 'description');
$this->headMeta('video', 'og:type');
$this->headMeta($video->main_img ? $this->serverUrl($video->main_img) : '', 'og:image');
$this->headMeta($this->serverUrl(), 'og:url');
$this->headMeta($escaper->escapeHtml($video->lead), 'og:description');

?>

<div class="video-single">
    <div class="headline-video">
        <div class="video-container-wraper">
            <iframe width="560" height="315" src="<?= $video->video_url ?>" frameborder="0" allowfullscreen></iframe>
        </div>
    </div>
    <div class="video-single-text">
        <div class="video-head-info">
            <div class="category">Video</div>
            <h1><?= $video->title ?></h1>

            <div class="author">Predavač: <strong><?= $video->sub_title ?></strong></div>
        </div>
        <div class="video-single-wrapper">
            <?= $this->partial('templates::partial/socialShares.phtml', ['item' => $video]); ?>
            <div class="video-text">
                <?= $video->body ?>

                <?= $this->partial('templates::partial/disqus.phtml'); ?>
            </div>
        </div>
    </div>

    <!--
    <div class="video-slider">
        <div class="heading">Pogledajte i</div>
        <div class="slider video-slider">
            <a href="/video-single.html" class="video-post">
                <div class="image-wrapper-none">
                    <img src="@@picture">

                    <div class="video-box-hover"><img src="/images/videos/play.png" alt="Play"></div>
                </div>
                <div class="video-box-content">
                    <div class="category">@@category</div>
                    <div class="title">@@title</div>
                    <div class="instructor">Predavač: @@instructor</div>
                </div>
            </a>
        </div>
    </div>
    -->
</div>