<?php if(isset($discussion)):?>
    <h2>Edit discussion</h2>
<?php else: ?>
    <h2>Create new discussion</h2>
<?php endif; ?>
<br/>

<form action="<?= $this->url('admin.discussions.action', ['action' => 'doedit', 'id' => $discussion ? $discussion->article_id : 0]) ?>" method="POST" class="form articleForm">
    <div class="form-group">
        <input type="text" class="form-control" placeholder="title" name="title" value="<?= $discussion ? $discussion->title : ''; ?>" />
    </div>

    <div class="form-group">
        <input type="text" class="form-control" placeholder="publish date" name="published_at" value="<?= $discussion ? $discussion->published_at : ''; ?>" />
        <i>format: yyyy-mm-dd H:i:s</i>
    </div>

    <div class="form-group">
        <input type="text" class="form-control" rows="3" placeholder="URL slug" name="slug" value="<?= $discussion ? $discussion->slug : ''; ?>">
    </div>

    <div class="form-group">
        <textarea id="body" class="form-control" name="body"><?= $discussion ? $discussion->body : '' ?></textarea>
    </div>

    <div class="form-group">
        <select name="status" id="status" class="form-control">
            <option value="0" <?= $discussion ? ($discussion->status == 0 ? 'selected' : '') : '' ?>>Unpublished</option>
            <option value="1" <?= $discussion ? ($discussion->status == 1 ? 'selected' : '') : '' ?>>Published</option>
        </select>
    </div>

    <div class="form-group">
        <?php foreach ($tags as $tag): ?>
            <label><?=$tag->name?></label>
            <input type="checkbox" name="tag_uuid[]" value="<?=$tag->tag_id?>" <?php if (in_array($tag->tag_id, $discussion->tagIds)):
                echo 'checked';
            endif; ?>/>
        <?php endforeach ?>
    </div>

    <button type="submit" class="btn btn-default">Save</button>
    <a href="<?= $this->url('admin.discussions') ?>" class="btn btn-default">Cancel</a>
</form>

<script src="/js/tinymce/tinymce.min.js"></script>
<script src="/js/initTinyMce.js"></script>

<script>
    initMce('#body', '100%', 300, true);

    $('.articleForm').on('submit', function(e) {
        tinyMCE.triggerSave();
    });
</script>