<?php if(isset($discussion->article_id) && $discussion->article_id):?>
    <h2>Edit discussion</h2>
<?php else: ?>
    <h2>Create new discussion</h2>
<?php endif; ?>
<br/>

<!-- Make better style with the theme css/html - notify -->
<?php if($errors): ?>
    <?php foreach($errors as $input => $inputErrors): ?>
        <div class="bg-danger" style="padding:0.5em; margin:0.5em;">
            <?= $input ?>
            <ul>
            <?php foreach($inputErrors as  $error): ?>
                <li><?= $error ?></li>
            <?php endforeach; ?>
            <ul/>
        </div>
    <?php endforeach;?>
    <br/>
<?php endif; ?>

<form action="<?= $this->url('admin.discussions.action', ['action' => 'save', 'id' => $discussion ? $discussion->article_id : 0]) ?>" method="POST" class="form articleForm">
    <div class="form-group">
        <input type="text" class="form-control" placeholder="title" name="title" value="<?= $discussion ? $discussion->title : ''; ?>" />
    </div>

    <div class="form-group">
        <input type="text" class="form-control" placeholder="publish date" name="published_at" value="<?= $discussion ? $discussion->published_at : ''; ?>" />
        <i>format: yyyy-mm-dd H:i:s</i>
    </div>

    <div class="form-group">
        <input type="text" class="form-control" rows="3" placeholder="URL slug" name="slug" value="<?= $discussion ? $discussion->slug : ''; ?>">
    </div>

    <div class="form-group">
        <textarea id="body" class="form-control" name="body"><?= $discussion ? $discussion->body : '' ?></textarea>
    </div>

    <div class="form-group">
        <select name="status" id="status" class="form-control">
            <option value="0" <?= $discussion ? ($discussion->status == 0 ? 'selected' : '') : '' ?>>Unpublished</option>
            <option value="1" <?= $discussion ? ($discussion->status == 1 ? 'selected' : '') : '' ?>>Published</option>
        </select>
    </div>

    <div class="form-group">
        <select multiple name="tags[]" style="width: 100%;">
            <?php foreach($tags as $tag): ?>
                <option value="<?= $tag->tag_id ?>" <?= (isset($discussion->tags) && in_array($tag->tag_id, $discussion->tags)) ? 'selected' : '' ?>>
                    <?= $tag->name ?>
                </option>
            <?php endforeach; ?>
        </select>
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-default">Save</button>
        <a href="<?= $this->url('admin.discussions') ?>" class="btn btn-default">Cancel</a>

        <?php if(isset($discussion->article_id) && $discussion->article_id): ?>
        <a href="<?= $this->url('admin.discussions.action', ['action' => 'delete', 'id' => $discussion->article_id]) ?>"
           onclick="if(!confirm('Are you sure?')){return false;}" class="btn btn-danger pull-right">
            Delete
        </a>
        <?php endif; ?>
    </div>
</form>

<script src="/js/tinymce/tinymce.min.js"></script>
<script src="/js/initTinyMce.js"></script>

<?php
$this->inlineScript()->appendScript("
    $(document).ready(function() {
        initMce('#body', '100%', 300, true);

        $('.articleForm').on('submit', function(e) {
            tinyMCE.triggerSave();
        });
    });
");
?>