<div class="row">
    <h2 class="col-md-6">Discussions list</h2>
    <div class="col-md-6">
        <a href="<?= $this->url('admin.discussions.action', ['action' => 'edit', 'id' => 0]) ?>" style="margin-top:20px;"
           class="btn btn-default pull-right btn-success"> Create new discussion
        </a>
    </div>
</div><br/>

<?php if($list->getTotalItemCount() > 0): ?>
    <table class="table table-hover table-striped ">
        <thead>
        <tr>
            <th>Title</th>
            <th>Published</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($list as $one): ?>
            <tr>
                <td><?= $one->title ?></td>
                <td style="width:90px;"><?= date("d.m.Y", strtotime($one->published_at)); ?></td>
                <td style="width:70px;">
                        <span class="pull-right">
                            <a href="<?= $this->url('admin.discussions.action', ['action' => 'edit', 'id' => $one->article_id]) ?>">
                                <i class="glyphicon glyphicon-pencil"></i></a> &nbsp; 
                            <a href="<?= $this->url('admin.discussions.action', ['action' => 'delete', 'id' => $one->article_id]) ?>"
                               onclick="if(!confirm('Are you sure?')){return false;}" class="text-danger">
                                <i class="glyphicon glyphicon-trash"></i>
                            </a>
                        </span>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

    <?= $this->paginationControl($list, 'Sliding', 'admin/pagination', ['route' => 'admin.discussions']) ?>

<?php else: ?>
    <div class="jumbotron text-center">
        <h3>There are no discussions!</h3>
    </div>
<?php endif; ?>