<form class="form" action="" method="POST">


    <input type="text" class="form-control" placeholder="title" name="title" value="<?php
    if (isset($data['title'])) { echo $data['title']; }
    ?>" /><br/>
    <?php if (isset($errors['title'])):?>
        <?php foreach ($errors['title'] as $msg): ?>
            <span><?=$msg?></span>
        <?php endforeach ?>
    <?php endif ?>

    <input type="text" class="form-control" placeholder="publish date" name="publishedAt"><br/>
    <?php if (isset($errors['publishedAt'])):?>
        <?php foreach ($errors['publishedAt'] as $msg): ?>
            <span><?=$msg?></span>
        <?php endforeach ?>
    <?php endif ?>

    <input type="text" class="form-control" placeholder="intro..." name="lead" value="<?php
    if (isset($data['lead'])) { echo $data['lead']; }
    ?>" /><br/>
    <?php if (isset($errors['lead'])):?>
        <?php foreach ($errors['lead'] as $msg): ?>
            <span><?=$msg?></span>
        <?php endforeach ?>
    <?php endif ?>

    <input type="text" class="form-control" placeholder="text..." name="body" value="<?php
    if (isset($data['body'])) { echo $data['body']; }
    ?>" /><br/>
    <?php if (isset($errors['body'])):?>
        <?php foreach ($errors['body'] as $msg): ?>
            <span><?=$msg?></span>
        <?php endforeach ?>
    <?php endif ?>

    <button class="btn btn-lg btn-primary btn-block" type="submit">Create</button>
</form>
