<div class="">
    <div class="page-title">
        <div class="title_left">
            <h3>Menu Items
                <small> / List of items in the menu (top, footer and side menu).</small>
            </h3>
        </div>
        <div class="title_right">
            <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
                      <button class="btn btn-default" type="button">Go!</button>
                    </span>
                </div>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <a href="<?= $this->url('admin.menu.action', ['action' => 'edit', 'id' => 0]) ?>"
                       class="btn btn-default pull-right btn-success"> Add new Menu Item
                    </a>

                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <?php if($menuNestedItems): ?>
                        <div class="panel-body">
                            <div class="nested-list dd with-margins"
                                 data-url="<?= $this->url('admin.menu.action', ['action' => 'updateOrder', 'id' => 0]) ?>">
                                <?= $this->partial('partial/menu-level', ['menuNestedItems' => $menuNestedItems]); ?>
                            </div>
                        </div>
                    <?php else: ?>
                        <div class="col-md-offset-3 col-sm-offset-3 col-md-6 col-sm-6 col-xs-12">
                            <div class="jumbotron text-center">
                                <h3>The menu is not created yet!</h3>
                            </div>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
</div>

<blockquote class="reordering blockquote-green" style="display: none;">
    <p><strong>...</strong></p>
</blockquote>

<?php
$this->inlineScript()->appendScript("
    $(document).ready(function() {
        buildNestableTree();
    });

function buildNestableTree(){
    // Nestable menu items - admin
    var t = $('.dd').nestable({'maxDepth': 3});
    var nestableJson = JSON.stringify(t.nestable('serialize'));
    var updateOutput = function () {
        if (JSON.stringify(t.nestable('serialize')) == nestableJson) {
            return false;
        }

        nestableJson = JSON.stringify(t.nestable('serialize'));
        $('.reordering p strong').text('Reordering...');
        $('.reordering').show();

        $.post(this.getAttribute('data-url'), {'order': JSON.stringify(t.nestable('serialize'))}, function (res) {
            if (res.status) {
                $('.reordering p strong').text('Done.');
            }
        });
    };

    t.on('change', updateOutput);
}
");
?>