FROM mysql:latest
COPY ./mysqld.cnf /etc/mysql/mysql.conf.d/mysqld.cnf

# add to your machine
#RUN mysql -u root -psecret -e 'create database pulsonlinepulsar_testing;'
#RUN cat /etc/mysql/mysql.conf.d/mysqld.cnf