<!-- Flat style parent and children items -->
<ul>
    <?php foreach($this->menu()->getFooterMenu() as $item): ?>
        <?php if($item['children']): ?>
            <?php foreach($item['children'] as $child): ?>
                <li><a href="<?= $this->menuUrl($child) ?>"><?= $child['title'] ?></a></li>
            <?php endforeach; ?>
        <?php else: ?>
            <li><a href="<?= $this->menuUrl($item) ?>"><?= $item['title'] ?></a></li>
        <?php endif; ?>
    <?php endforeach; ?>
</ul>