<!-- this theme support two level navigation -->
<nav>
    <ul class="clearfix">
        <!-- dynamic two level menu -->
        <?php foreach($this->menu()->getHeaderMenu() as $item): ?>
            <li>
            <?php if(!$item['children']): ?>
                <?php $href = $this->menuUrl($item) ?>
                <a href="<?= $href ?>" <?= (strpos($href, 'http') === 0) ? 'target="_blank"' : '' ?>>
                    <?= $item['title'] ?>
                </a>
            <?php else: ?>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">
                        <?= $item['title'] ?> <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <?php foreach($item['children'] as $child): ?>
                            <?php $href = $this->menuUrl($child) ?>
                            <li>
                                <a href="<?= $href ?>" <?= (strpos($href, 'http') === 0) ? 'target="_blank"' : '' ?>>
                                    <?= $child['title'] ?>
                                </a>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </li>
            <?php endif; ?>
            </li>
        <?php endforeach; ?>

        <!-- Custom links in the menu -->
        <li class="white">
            <a href="<?= $this->url('fake-it') ?>" class="btn btn-white">PRIKLJUČI SE</a>
        </li>
        <li class="blue">
            <a href="<?= $this->url('fake-it') ?>" class="btn btn-blue">NAPIŠI ČLANAK</a>
        </li>
    </ul>
</nav>