<!-- this theme support two level navigation -->
<nav>
    <ul class="clearfix">
        <!-- dynamic two level menu -->
        <?php foreach($this->menu()->getHeaderMenu() as $item): ?>
            <li>
            <?php if(!$item['children']): ?>
                <a href="<?= $this->menuUrl($item) ?>"><?= $item['title'] ?></a>
            <?php else: ?>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">
                        <?= $item['title'] ?> <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <?php foreach($item['children'] as $child): ?>
                            <li><a href="<?= $this->menuUrl($child) ?>"><?= $child['title'] ?></a></li>
                        <?php endforeach; ?>
                    </ul>
                </li>
            <?php endif; ?>
            </li>
        <?php endforeach; ?>

        <!-- Custom links in the menu -->
        <li class="white">
            <button class="btn btn-white">PRIKLJUČI SE</button>
        </li>
        <li class="blue">
            <button class="btn btn-blue">NAPIŠI ČLANAK</button>
        </li>
    </ul>
</nav>