<?php
$escaper = new \Zend\Escaper\Escaper;

if($item->type == 1){
    $url         = $this->url('post', ['segment_1' => $item->category_slug, 'segment_2' => $item->slug]);
    $description = $item->lead;
}
else if($item->type == 2){
    $url         = $this->url('video', ['video_slug' => $item->slug]);
    $description = $item->lead;
}
else if($item->type == 3){
    $url         = $this->url('event', ['event_slug' => $item->slug]);
    $description = $item->sub_title;
}

?>

<!-- for Facebook -->
<?php $this->headMeta($escaper->escapeHtml($item->title), 'og:title'); ?>
<?php $this->headMeta($escaper->escapeHtml('article'), 'og:type'); ?>
<?php $this->headMeta($this->serverUrl($item->main_img), 'og:image'); ?>
<?php $this->headMeta($escaper->escapeHtml($this->serverUrl($url)), 'og:url'); ?>
<?php $this->headMeta($escaper->escapeHtml($description), 'og:description'); ?>

<div class="social-share">
    <div class="social-icons social-icon__vertical">
        <div class="social-icon-shared">
            <strong class="total-shares">0</strong>
            <span>Podeljeno</span>
        </div>

        <a href="<?= $url ?>" target="_blank" data-title="<?= $item->title ?>"
           data-image="<?= $this->serverUrl($item->main_img) ?>">
            <button class="btn btn-white social facebook-share icon-facebook"></button>
        </a>
        <a href="<?= $url ?>" target="_blank" data-title="<?= $item->title ?>" data-image="<?= $item->main_img ?>">
            <button class="btn btn-white social twitter-share icon-twitter"></button>
        </a>
        <a href="<?= $url ?>" target="_blank" data-title="<?= $item->title ?>" data-image="<?= $item->main_img ?>">
            <button class="btn btn-white social linkedin-share icon-linkedin"></button>
        </a>
    </div>
</div>
