<?php if(isset($tag->tag_id) && $tag->tag_id): ?>
    <h2>Edit tag "<?= $tag->name ?>"</h2>
<?php else: ?>
    <h2>Add new tag</h2>
<?php endif; ?>
<br/>

<!-- Make better style with the theme css/html - notify -->
<?php if($errors): ?>
    <?php foreach($errors as $input => $inputErrors): ?>
        <div class="bg-danger" style="padding:0.5em; margin:0.5em;">
            <?= $input ?>
            <ul>
                <?php foreach($inputErrors as  $error): ?>
                    <li><?= $error ?></li>
                <?php endforeach; ?>
            <ul/>
        </div>
    <?php endforeach;?>
    <br/>
<?php endif; ?>


<form action="<?= $this->url('admin.tags.action', ['action' => 'save', 'id' => $tag ? $tag->tag_id : 0]) ?>"
      method="POST">
    <div class="form-group">
        <input type="text" class="form-control" name="name" placeholder="Tag name" value="<?= $tag ? $tag->name : '' ?>">
    </div>

    <div class="form-group">
        <input type="text" class="form-control" name="slug" placeholder="URL slug" value="<?= $tag ? $tag->slug : '' ?>">
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-default">Save</button>
        <a href="<?= $this->url('admin.tags') ?>" class="btn btn-default">Cancel</a>

        <?php if($tag): ?>
            <a href="<?= $this->url('admin.tags.action', ['action' => 'delete', 'id' => $tag->tag_id]) ?>"
               onclick="if(!confirm('Are you sure?')){return false;}" class="btn btn-danger pull-right">
                Delete
            </a>
        <?php endif; ?>
    </div>
</form>
<br/>