<?php if($tag): ?>
    <h2>Edit tag "<?= $tag->name ?>"</h2>
<?php else: ?>
    <h2>Add new tag</h2>
<?php endif; ?>
<br/>


<form action="<?= $this->url('admin.tags.action', ['action' => 'doedit', 'id' => $tag ? $tag->tag_id : 0]) ?>"
      method="POST">
    <div class="form-group">
        <input type="text" class="form-control" name="name" value="<?= $tag ? $tag->name : '' ?>">
    </div>

    <div class="form-group">
        <input type="text" class="form-control" name="slug" value="<?= $tag ? $tag->slug : '' ?>">
    </div>

    <button type="submit" class="btn btn-default">Save</button>
    <a href="<?= $this->url('admin.tags') ?>" class="btn btn-default">Cancel</a>
</form>
<br/>