<?php
$this->headLink()
    ->prependStylesheet('http://getbootstrap.com/examples/jumbotron-narrow/jumbotron-narrow.css')
    ->prependStylesheet('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css')
    ->prependStylesheet('https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css');

$this->inlineScript()
    ->prependFile('/js/app.js')
    ->prependFile('/js/jquery.pjax.js')
    ->prependFile('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js')
    ->prependFile('https://code.jquery.com/jquery-2.2.4.min.js');
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/favicon.ico">

    <?= $this->headTitle('Unfinished')->setSeparator('::')->setAutoEscape(false) ?>
    <?= $this->headMeta(); ?>
    <?= $this->headLink(); ?>
</head>
<body>
<div class="container">
    <div class="header clearfix">
        <nav>
            <ul class="nav nav-pills pull-right">
                <li role="presentation"><a href="<?= $this->url('home') ?>">Home</a></li>
                <li role="presentation"><a href="<?= $this->url('about') ?>">About</a></li>
                <li role="presentation"><a href="<?= $this->url('contact') ?>">Contact</a></li>
                <li role="presentation" class="active"><a href="<?= $this->url('auth', ['action' => 'login']) ?>">Login</a></li>
            </ul>
        </nav>
        <h3 class="text-muted">Unfinished&trade;</h3>
    </div>

    <div id="content">
        <?= $this->content; ?>
    </div>

    <footer class="footer">
        <p>&copy; PHP Serbia 2012 - <?= date('Y') ?> Made with ♥ in Serbia</p>
    </footer>
</div>
<?= $this->inlineScript(); ?>
</body>
</html>