<!doctype html>
<html class="no-js">
<head>
    <meta charset="utf-8">
    <title>PHP Srbija 2017</title>
    <meta name="description" content="PHP Srbija 2017">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
    <link rel="shortcut icon" href="/favicon.ico">
    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
    <link rel="stylesheet" href="/css/vendor.css">
    <link rel="stylesheet" href="/css/main.css">
    <script src="/vendor/modernizr.js"></script>
</head>
<body>
<!--[if lt IE 9]>
<p class="browsehappy">You are using an <strong>outdated</strong> browser.
    Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
<![endif]-->
<div class="wrapper">
    <header class="clearfix">
        <button class="btn btn-header-mobile icon-menu"></button>
        <button class="btn btn-header-mobile icon-search"></button>
        <a class="icon-logo" href="<?= $this->url('home') ?>"><img src="/images/logo.png"></a>
        <a href="<?= $this->url('fake-it') ?>" class="btn btn-header-mobile icon-user"></a>
        <?= $this->partial('templates::partial/header.phtml'); ?>
    </header>

    <?= $this->content ?>

    <footer>
        <div class="footer-wrapper">
            <div class="read">Čitaj naš newsletter i kodiraćeš bolje</div>
            <form method="post" action="">
                <div class="input-wrapper">
                    <input type="email" name="email" id="email" placeholder="Tvoja email adresa">
                    <button class="btn btn-submit" id="submit" title="Posalji"></button>
                </div>
            </form>
            <div class="footer-nav-social-wrapper">
                <?= $this->partial('templates::partial/footer.phtml'); ?>
                <div class="right">
                    <div class="follow-us">Pratite PHP Srbiju:</div>
                    <div class="social-icons">
                        <a href="#" target="_blank">
                            <button class="btn btn-white social icon-facebook"></button>
                        </a>
                        <a href="#" target="_blank">
                            <button class="btn btn-white social icon-twitter"></button>
                        </a>
                        <a href="#" target="_blank">
                            <button class="btn btn-white social instagram">
                                <span class="icon-instagram">
                                    <span class="path1"></span>
                                    <span class="path2"></span>
                                    <span class="path3"></span>
                                    <span class="path4"></span>
                                </span>
                            </button>
                        </a>
                        <a href="#" target="_blank">
                            <button class="btn btn-white social icon-linkedin"></button>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="separator">
            <div class="copy">&copy; 2017 PHP SRBIJA. ALL RIGHTS RESERVED.</div>
        </div>
    </footer>

    <script src="/vendor/vendor.js"></script>
    <!-- Google Analytics: uncomment and change UA-XXXXX-X to be your site's ID.
        <script>
          (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
          function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
          e=o.createElement(i);r=o.getElementsByTagName(i)[0];
          e.src='//www.google-analytics.com/analytics.js';
          r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
          ga('create','UA-XXXXX-X');ga('send','pageview');
        </script>
        Load it from config file -->
    <script src="/vendor/dependencies.js"></script>
    <script src="/js/main.js"></script>
</div>