<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/favicon.ico">
    <title>Homepage</title>

    <!-- CSS -->
    <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="http://getbootstrap.com/assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">
</head>
<body>
<!-- Navbar -->
<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="<?= $this->url('home') ?>">Logo</a>
        </div>
        <div>
            <?= $this->partial('templates::partial/header.phtml'); ?>

            <ul class="nav navbar-nav pull-right">
                <li><a href="#">Login</a></li>
                <li><a href="#">Register</a></li>
                <li><a href="#">Profile</a></li>
                <li><a href="#">Pretraga</a></li>
            </ul>
        </div>
    </div>
</nav>

<!-- Page content -->
<div class="container">
    <?= $this->content ?>
</div>

<!-- Footer -->
<footer class="footer">
    <hr>
    <div class="container">
        <p class="text-muted">Your sexy footer.</p>
        <!-- Flat style parent and children items -->
        <ul class="">
            <?php foreach($this->menu()->getHeaderMenu() as $item): ?>
                <?php if($item['children']): ?>
                    <?php foreach($item['children'] as $child): ?>
                        <?php $link = $child['href'] ? : ($child['article_slug'] ? : ($child['category_slug']) ? : '#') ?>
                        <li><a href="<?= $link ?>"><?= $child['title'] ?></a></li>
                    <?php endforeach; ?>
                <?php else: ?>
                    <?php $link = $item['href'] ? : ($item['article_slug'] ? : ($item['category_slug']) ? : '#') ?>
                    <li><a href="<?= $link ?>"><?= $item['title'] ?></a></li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </div>
</footer>

<!-- JavaScript  -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="http://getbootstrap.com/assets/js/vendor/jquery.min.js"><\/script>')</script>
<script src="http://getbootstrap.com/dist/js/bootstrap.min.js"></script>
</body>
</html>
