<!doctype html>
<html class="no-js">
<head>
    <meta charset="utf-8">
    <title>PHP Srbija 2017</title>
    <meta name="description" content="PHP Srbija 2017">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
    <link rel="shortcut icon" href="/favicon.ico">
    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
    <link rel="stylesheet" href="/css/main.css">
    <link rel="stylesheet" href="/css/vendor.css">
    <script src="/vendor/modernizr.js"></script>


    <!-- favicon for all devices... -->
    <link rel="apple-touch-icon" sizes="57x57" href="/images/favico/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/images/favico/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/images/favico/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/images/favico/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/images/favico/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/images/favico/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/images/favico/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/images/favico/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/images/favico/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192" href="/images/favico/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/images/favico/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/images/favico/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/images/favico/favicon-16x16.png">
    <link rel="manifest" href="/images/favico/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">

</head>
<body>
<!--[if lt IE 9]>
<p class="browsehappy">You are using an <strong>outdated</strong> browser.
    Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
<![endif]-->
<div class="wrapper">
    <header class="clearfix">
        <button class="btn btn-header-mobile icon-menu"></button>
        <!-- <a href="/vesti/uskoro" class="btn btn-header-mobile icon-search"></a> -->
        <a title="PHP Srbija" class="icon-logo" href="<?= $this->url('home') ?>"><img alt="PHP Srbija"
                                                                                      src="/images/logo.png"></a>
        <a href="/vesti/uskoro" class="btn btn-header-mobile icon-user"></a>
        <?= $this->partial('templates::partial/header.phtml'); ?>
    </header>

    <?= $this->content ?>

    <footer>
        <div class="footer-wrapper">
            <div class="read">Čitaj naš newsletter i kodiraćeš bolje</div>
            <form method="post" action="<?= $this->url('newsletter-post') ?>">
                <div class="input-wrapper">
                    <input type="email" name="email" id="email" placeholder="Tvoja email adresa">
                    <button class="btn btn-submit" id="submit" title="Posalji"></button>
                </div>
            </form>
            <div class="footer-nav-social-wrapper">
                <?= $this->partial('templates::partial/footer.phtml'); ?>
                <div class="right">
                    <div class="follow-us">Pratite PHP Srbiju:</div>
                    <div class="social-icons">
                        <a href="https://sr-rs.facebook.com/udruzenjeprogramera.rs" target="_blank">
                            <button class="btn btn-white social icon-facebook"></button>
                        </a>
                        <a href="https://twitter.com/phpsrbija" target="_blank">
                            <button class="btn btn-white social icon-twitter"></button>
                        </a>
                        <a href="https://www.instagram.com/phpsrbija/" target="_blank">
                            <button class="btn btn-white social instagram">
                                    <span class="icon-instagram">
                                        <span class="path1"></span>
                                        <span class="path2"></span>
                                        <span class="path3"></span>
                                        <span class="path4"></span>
                                    </span>
                            </button>
                        </a>
                        <a href="https://www.linkedin.com/company-beta/2909733/" target="_blank">
                            <button class="btn btn-white social icon-linkedin"></button>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="separator">
            <div class="copy">&copy; 2017 PHP SRBIJA. ALL RIGHTS RESERVED.</div>
        </div>
    </footer>

    <script src="/vendor/vendor.js"></script>
        <script>
          (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
          function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
          e=o.createElement(i);r=o.getElementsByTagName(i)[0];
          e.src='//www.google-analytics.com/analytics.js';
          r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
          ga('create','UA-37654719-2');ga('send','pageview');
        </script>
    <script src="/vendor/dependencies.js"></script>
    <script src="/js/main.js"></script>
    <script src="/js/share.js"></script>
</div>
<body>
</html>